#import <Foundation/Foundation.h>
@interface EatSingMBProgressHUDxm: NSObject
+ (BOOL)ZNshowhudaddedtoanimatedrun:(NSInteger)Eat;
+ (BOOL)ZUhidehudforviewanimatedrun:(NSInteger)Eat;
+ (BOOL)HQhudforviewrun:(NSInteger)Eat;
+ (BOOL)SFcommoninitrun:(NSInteger)Eat;
+ (BOOL)VJinitwithframerun:(NSInteger)Eat;
+ (BOOL)qXinitwithcoderrun:(NSInteger)Eat;
+ (BOOL)oQinitwithviewrun:(NSInteger)Eat;
+ (BOOL)iEdeallocrun:(NSInteger)Eat;
+ (BOOL)CVshowanimatedrun:(NSInteger)Eat;
+ (BOOL)yRhideanimatedrun:(NSInteger)Eat;
+ (BOOL)fDhideanimatedafterdelayrun:(NSInteger)Eat;
+ (BOOL)nGhandlegracetimerrun:(NSInteger)Eat;
+ (BOOL)TGhandleminshowtimerrun:(NSInteger)Eat;
+ (BOOL)NXhandlehidetimerrun:(NSInteger)Eat;
+ (BOOL)eGdidmovetosuperviewrun:(NSInteger)Eat;
+ (BOOL)OUshowusinganimationrun:(NSInteger)Eat;
+ (BOOL)GBhideusinganimationrun:(NSInteger)Eat;
+ (BOOL)pUanimateinwithtypecompletionrun:(NSInteger)Eat;
+ (BOOL)CMdonerun:(NSInteger)Eat;
+ (BOOL)vBsetupviewsrun:(NSInteger)Eat;
+ (BOOL)BGupdateindicatorsrun:(NSInteger)Eat;
+ (BOOL)UPupdateviewsforcolorrun:(NSInteger)Eat;
+ (BOOL)pQupdatebezelmotioneffectsrun:(NSInteger)Eat;
+ (BOOL)PFupdateconstraintsrun:(NSInteger)Eat;
+ (BOOL)QElayoutsubviewsrun:(NSInteger)Eat;
+ (BOOL)eOupdatepaddingconstraintsrun:(NSInteger)Eat;
+ (BOOL)CFapplyprioritytoconstraintsrun:(NSInteger)Eat;
+ (BOOL)nXsetmoderun:(NSInteger)Eat;
+ (BOOL)dQsetcustomviewrun:(NSInteger)Eat;
+ (BOOL)xDsetoffsetrun:(NSInteger)Eat;
+ (BOOL)fBsetmarginrun:(NSInteger)Eat;
+ (BOOL)eUsetminsizerun:(NSInteger)Eat;
+ (BOOL)JZsetsquarerun:(NSInteger)Eat;
+ (BOOL)xSsetprogressobjectdisplaylinkrun:(NSInteger)Eat;
+ (BOOL)JPsetprogressobjectrun:(NSInteger)Eat;
+ (BOOL)pFsetprogressrun:(NSInteger)Eat;
+ (BOOL)LUsetcontentcolorrun:(NSInteger)Eat;
+ (BOOL)QOsetdefaultmotioneffectsenabledrun:(NSInteger)Eat;
+ (BOOL)KOsetnsprogressdisplaylinkenabledrun:(NSInteger)Eat;
+ (BOOL)oSupdateprogressfromprogressobjectrun:(NSInteger)Eat;
+ (BOOL)JMregisterfornotificationsrun:(NSInteger)Eat;
+ (BOOL)MOunregisterfromnotificationsrun:(NSInteger)Eat;
+ (BOOL)USstatusbarorientationdidchangerun:(NSInteger)Eat;
+ (BOOL)VSupdateforcurrentorientationanimatedrun:(NSInteger)Eat;

@end
