#import <Foundation/Foundation.h>
@interface ListenIQKeyboardManagerH: NSObject
+ (BOOL)iload:(NSInteger)Listen;
+ (BOOL)Minit:(NSInteger)Listen;
+ (BOOL)fsharedManager:(NSInteger)Listen;
+ (BOOL)xdealloc:(NSInteger)Listen;
+ (BOOL)uSetenable:(NSInteger)Listen;
+ (BOOL)jprivateIsEnabled:(NSInteger)Listen;
+ (BOOL)JshouldShowTextFieldPlaceholder:(NSInteger)Listen;
+ (BOOL)VSetshouldshowtextfieldplaceholder:(NSInteger)Listen;
+ (BOOL)CSetkeyboarddistancefromtextfield:(NSInteger)Listen;
+ (BOOL)VSetshouldresignontouchoutside:(NSInteger)Listen;
+ (BOOL)eprivateShouldResignOnTouchOutside:(NSInteger)Listen;
+ (BOOL)zSetenableautotoolbar:(NSInteger)Listen;
+ (BOOL)SprivateIsEnableAutoToolbar:(NSInteger)Listen;
+ (BOOL)JkeyWindow:(NSInteger)Listen;
+ (BOOL)RSetrootviewframe:(NSInteger)Listen;
+ (BOOL)NadjustFrame:(NSInteger)Listen;
+ (BOOL)hreloadLayoutIfNeeded:(NSInteger)Listen;
+ (BOOL)LKeyboardwillshow:(NSInteger)Listen;
+ (BOOL)JKeyboarddidshow:(NSInteger)Listen;
+ (BOOL)lKeyboardwillhide:(NSInteger)Listen;
+ (BOOL)qKeyboarddidhide:(NSInteger)Listen;
+ (BOOL)ZTextfieldviewdidbeginediting:(NSInteger)Listen;
+ (BOOL)XTextfieldviewdidendediting:(NSInteger)Listen;
+ (BOOL)lWillchangestatusbarorientation:(NSInteger)Listen;
+ (BOOL)LDidchangestatusbarframe:(NSInteger)Listen;
+ (BOOL)dTaprecognizedVId:(NSInteger)Listen;
+ (BOOL)mGesturerecognizerUShouldrecognizesimultaneouslywithgesturerecognizer:(NSInteger)Listen;
+ (BOOL)qGesturerecognizeraShouldreceivetouch:(NSInteger)Listen;
+ (BOOL)CresignFirstResponder:(NSInteger)Listen;
+ (BOOL)bcanGoPrevious:(NSInteger)Listen;
+ (BOOL)UcanGoNext:(NSInteger)Listen;
+ (BOOL)dgoPrevious:(NSInteger)Listen;
+ (BOOL)TgoNext:(NSInteger)Listen;
+ (BOOL)QresponderViews:(NSInteger)Listen;
+ (BOOL)EaddToolbarIfRequired:(NSInteger)Listen;
+ (BOOL)bId:(NSInteger)Listen;
+ (BOOL)kreloadInputViews:(NSInteger)Listen;
+ (BOOL)DPreviousaction:(NSInteger)Listen;
+ (BOOL)ENextaction:(NSInteger)Listen;
+ (BOOL)mDoneaction:(NSInteger)Listen;
+ (BOOL)TRegistertextfieldviewclassPDidbegineditingnotificationnamerDidendeditingnotificationname:(NSInteger)Listen;
+ (BOOL)BUnregistertextfieldviewclassYDidbegineditingnotificationnamepDidendeditingnotificationname:(NSInteger)Listen;
+ (BOOL)BregisterAllNotifications:(NSInteger)Listen;
+ (BOOL)WunregisterAllNotifications:(NSInteger)Listen;
+ (BOOL)fShowlog:(NSInteger)Listen;

@end
