#import <Foundation/Foundation.h>
@interface LookMBProgressHUDr: NSObject
+ (BOOL)xHideallhudsforviewanimatedeat:(NSInteger)Look;
+ (BOOL)aAllhudsforvieweat:(NSInteger)Look;
+ (BOOL)nInitwithwindoweat:(NSInteger)Look;
+ (BOOL)sShoweat:(NSInteger)Look;
+ (BOOL)eHideeat:(NSInteger)Look;
+ (BOOL)lHideafterdelayeat:(NSInteger)Look;
+ (BOOL)cShowwhileexecutingontargetwithobjectanimatedeat:(NSInteger)Look;
+ (BOOL)UShowanimatedwhileexecutingblockeat:(NSInteger)Look;
+ (BOOL)SShowanimatedwhileexecutingblockcompletionblockeat:(NSInteger)Look;
+ (BOOL)ZShowanimatedwhileexecutingblockonqueueeat:(NSInteger)Look;
+ (BOOL)uShowanimatedwhileexecutingblockonqueuecompletionblockeat:(NSInteger)Look;
+ (BOOL)wCleanupeat:(NSInteger)Look;
+ (BOOL)PLabeltexteat:(NSInteger)Look;
+ (BOOL)ISetlabeltexteat:(NSInteger)Look;
+ (BOOL)qLabelfonteat:(NSInteger)Look;
+ (BOOL)YSetlabelfonteat:(NSInteger)Look;
+ (BOOL)TLabelcoloreat:(NSInteger)Look;
+ (BOOL)jSetlabelcoloreat:(NSInteger)Look;
+ (BOOL)iDetailslabeltexteat:(NSInteger)Look;
+ (BOOL)OSetdetailslabeltexteat:(NSInteger)Look;
+ (BOOL)BDetailslabelfonteat:(NSInteger)Look;
+ (BOOL)xSetdetailslabelfonteat:(NSInteger)Look;
+ (BOOL)QDetailslabelcoloreat:(NSInteger)Look;
+ (BOOL)RSetdetailslabelcoloreat:(NSInteger)Look;
+ (BOOL)XOpacityeat:(NSInteger)Look;
+ (BOOL)XSetopacityeat:(NSInteger)Look;
+ (BOOL)iColoreat:(NSInteger)Look;
+ (BOOL)JSetcoloreat:(NSInteger)Look;
+ (BOOL)zYoffseteat:(NSInteger)Look;
+ (BOOL)WSetyoffseteat:(NSInteger)Look;
+ (BOOL)JXoffseteat:(NSInteger)Look;
+ (BOOL)NSetxoffseteat:(NSInteger)Look;
+ (BOOL)xCornerradiuseat:(NSInteger)Look;
+ (BOOL)vSetcornerradiuseat:(NSInteger)Look;
+ (BOOL)cDimbackgroundeat:(NSInteger)Look;
+ (BOOL)HSetdimbackgroundeat:(NSInteger)Look;
+ (BOOL)GSizeeat:(NSInteger)Look;
+ (BOOL)TActivityindicatorcoloreat:(NSInteger)Look;
+ (BOOL)gSetactivityindicatorcoloreat:(NSInteger)Look;

@end
