#import <Foundation/Foundation.h>
@interface RunMBProgressHUDl: NSObject
+ (BOOL)JShowhudaddedtoTAnimated:(NSInteger)Run;
+ (BOOL)VHidehudforviewIAnimated:(NSInteger)Run;
+ (BOOL)RHudforview:(NSInteger)Run;
+ (BOOL)acommonInit:(NSInteger)Run;
+ (BOOL)yInitwithframe:(NSInteger)Run;
+ (BOOL)LInitwithcoder:(NSInteger)Run;
+ (BOOL)DInitwithview:(NSInteger)Run;
+ (BOOL)wdealloc:(NSInteger)Run;
+ (BOOL)jShowanimated:(NSInteger)Run;
+ (BOOL)AHideanimated:(NSInteger)Run;
+ (BOOL)QHideanimatedkAfterdelay:(NSInteger)Run;
+ (BOOL)lHandlegracetimer:(NSInteger)Run;
+ (BOOL)bHandleminshowtimer:(NSInteger)Run;
+ (BOOL)FHandlehidetimer:(NSInteger)Run;
+ (BOOL)KdidMoveToSuperview:(NSInteger)Run;
+ (BOOL)BShowusinganimation:(NSInteger)Run;
+ (BOOL)fHideusinganimation:(NSInteger)Run;
+ (BOOL)SAnimateinzWithtypeUCompletion:(NSInteger)Run;
+ (BOOL)fdone:(NSInteger)Run;
+ (BOOL)hsetupViews:(NSInteger)Run;
+ (BOOL)tupdateIndicators:(NSInteger)Run;
+ (BOOL)RUpdateviewsforcolor:(NSInteger)Run;
+ (BOOL)KupdateBezelMotionEffects:(NSInteger)Run;
+ (BOOL)OupdateConstraints:(NSInteger)Run;
+ (BOOL)rlayoutSubviews:(NSInteger)Run;
+ (BOOL)CupdatePaddingConstraints:(NSInteger)Run;
+ (BOOL)yApplyprioritynToconstraints:(NSInteger)Run;
+ (BOOL)ESetmode:(NSInteger)Run;
+ (BOOL)bSetcustomview:(NSInteger)Run;
+ (BOOL)iSetoffset:(NSInteger)Run;
+ (BOOL)qSetmargin:(NSInteger)Run;
+ (BOOL)nSetminsize:(NSInteger)Run;
+ (BOOL)GSetsquare:(NSInteger)Run;
+ (BOOL)lSetprogressobjectdisplaylink:(NSInteger)Run;
+ (BOOL)aSetprogressobject:(NSInteger)Run;
+ (BOOL)PSetprogress:(NSInteger)Run;
+ (BOOL)MSetcontentcolor:(NSInteger)Run;
+ (BOOL)qSetdefaultmotioneffectsenabled:(NSInteger)Run;
+ (BOOL)jSetnsprogressdisplaylinkenabled:(NSInteger)Run;
+ (BOOL)MupdateProgressFromProgressObject:(NSInteger)Run;
+ (BOOL)zregisterForNotifications:(NSInteger)Run;
+ (BOOL)WunregisterFromNotifications:(NSInteger)Run;
+ (BOOL)KStatusbarorientationdidchange:(NSInteger)Run;
+ (BOOL)lUpdateforcurrentorientationanimated:(NSInteger)Run;

@end
