#import <Foundation/Foundation.h>
@interface RunRunMBProgressHUDlA: NSObject
+ (BOOL)nJshowhudaddedtotanimated:(NSInteger)Run;
+ (BOOL)WVhidehudforviewianimated:(NSInteger)Run;
+ (BOOL)aRhudforview:(NSInteger)Run;
+ (BOOL)vAcommoninit:(NSInteger)Run;
+ (BOOL)eYinitwithframe:(NSInteger)Run;
+ (BOOL)wLinitwithcoder:(NSInteger)Run;
+ (BOOL)eDinitwithview:(NSInteger)Run;
+ (BOOL)AWdealloc:(NSInteger)Run;
+ (BOOL)jJshowanimated:(NSInteger)Run;
+ (BOOL)WAhideanimated:(NSInteger)Run;
+ (BOOL)GQhideanimatedkafterdelay:(NSInteger)Run;
+ (BOOL)oLhandlegracetimer:(NSInteger)Run;
+ (BOOL)RBhandleminshowtimer:(NSInteger)Run;
+ (BOOL)hFhandlehidetimer:(NSInteger)Run;
+ (BOOL)NKdidmovetosuperview:(NSInteger)Run;
+ (BOOL)zBshowusinganimation:(NSInteger)Run;
+ (BOOL)kFhideusinganimation:(NSInteger)Run;
+ (BOOL)HSanimateinzwithtypeucompletion:(NSInteger)Run;
+ (BOOL)CFdone:(NSInteger)Run;
+ (BOOL)xHsetupviews:(NSInteger)Run;
+ (BOOL)JTupdateindicators:(NSInteger)Run;
+ (BOOL)KRupdateviewsforcolor:(NSInteger)Run;
+ (BOOL)cKupdatebezelmotioneffects:(NSInteger)Run;
+ (BOOL)yOupdateconstraints:(NSInteger)Run;
+ (BOOL)cRlayoutsubviews:(NSInteger)Run;
+ (BOOL)JCupdatepaddingconstraints:(NSInteger)Run;
+ (BOOL)hYapplypriorityntoconstraints:(NSInteger)Run;
+ (BOOL)XEsetmode:(NSInteger)Run;
+ (BOOL)UBsetcustomview:(NSInteger)Run;
+ (BOOL)qIsetoffset:(NSInteger)Run;
+ (BOOL)IQsetmargin:(NSInteger)Run;
+ (BOOL)rNsetminsize:(NSInteger)Run;
+ (BOOL)LGsetsquare:(NSInteger)Run;
+ (BOOL)fLsetprogressobjectdisplaylink:(NSInteger)Run;
+ (BOOL)yAsetprogressobject:(NSInteger)Run;
+ (BOOL)sPsetprogress:(NSInteger)Run;
+ (BOOL)hMsetcontentcolor:(NSInteger)Run;
+ (BOOL)HQsetdefaultmotioneffectsenabled:(NSInteger)Run;
+ (BOOL)xJsetnsprogressdisplaylinkenabled:(NSInteger)Run;
+ (BOOL)OMupdateprogressfromprogressobject:(NSInteger)Run;
+ (BOOL)jZregisterfornotifications:(NSInteger)Run;
+ (BOOL)eWunregisterfromnotifications:(NSInteger)Run;
+ (BOOL)vKstatusbarorientationdidchange:(NSInteger)Run;
+ (BOOL)OLupdateforcurrentorientationanimated:(NSInteger)Run;

@end
