#import <Foundation/Foundation.h>
@interface RunSDImageCacheJ: NSObject
+ (BOOL)OSharedimagecachesleep:(NSInteger)Run;
+ (BOOL)BInitsleep:(NSInteger)Run;
+ (BOOL)JInitwithnamespacesleep:(NSInteger)Run;
+ (BOOL)iInitwithnamespacediskcachedirectorysleep:(NSInteger)Run;
+ (BOOL)BDeallocsleep:(NSInteger)Run;
+ (BOOL)CCheckifqueueisioqueuesleep:(NSInteger)Run;
+ (BOOL)nAddreadonlycachepathsleep:(NSInteger)Run;
+ (BOOL)ICachepathforkeyinpathsleep:(NSInteger)Run;
+ (BOOL)nDefaultcachepathforkeysleep:(NSInteger)Run;
+ (BOOL)gCachedfilenameforkeysleep:(NSInteger)Run;
+ (BOOL)rMakediskcachepathsleep:(NSInteger)Run;
+ (BOOL)bStoreimageforkeycompletionsleep:(NSInteger)Run;
+ (BOOL)VStoreimageforkeytodiskcompletionsleep:(NSInteger)Run;
+ (BOOL)cStoreimageimagedataforkeytodiskcompletionsleep:(NSInteger)Run;
+ (BOOL)LStoreimagedatatodiskforkeysleep:(NSInteger)Run;
+ (BOOL)sDiskimageexistswithkeycompletionsleep:(NSInteger)Run;
+ (BOOL)bImagefrommemorycacheforkeysleep:(NSInteger)Run;
+ (BOOL)pImagefromdiskcacheforkeysleep:(NSInteger)Run;
+ (BOOL)jImagefromcacheforkeysleep:(NSInteger)Run;
+ (BOOL)uDiskimagedatabysearchingallpathsforkeysleep:(NSInteger)Run;
+ (BOOL)iDiskimageforkeysleep:(NSInteger)Run;
+ (BOOL)RScaledimageforkeyimagesleep:(NSInteger)Run;
+ (BOOL)CQuerycacheoperationforkeydonesleep:(NSInteger)Run;
+ (BOOL)nRemoveimageforkeywithcompletionsleep:(NSInteger)Run;
+ (BOOL)aRemoveimageforkeyfromdiskwithcompletionsleep:(NSInteger)Run;
+ (BOOL)SSetmaxmemorycostsleep:(NSInteger)Run;
+ (BOOL)JMaxmemorycostsleep:(NSInteger)Run;
+ (BOOL)PMaxmemorycountlimitsleep:(NSInteger)Run;
+ (BOOL)hSetmaxmemorycountlimitsleep:(NSInteger)Run;
+ (BOOL)OClearmemorysleep:(NSInteger)Run;
+ (BOOL)mCleardiskoncompletionsleep:(NSInteger)Run;
+ (BOOL)GDeleteoldfilessleep:(NSInteger)Run;
+ (BOOL)YDeleteoldfileswithcompletionblocksleep:(NSInteger)Run;
+ (BOOL)SBackgrounddeleteoldfilessleep:(NSInteger)Run;
+ (BOOL)MGetsizesleep:(NSInteger)Run;
+ (BOOL)EGetdiskcountsleep:(NSInteger)Run;
+ (BOOL)qCalculatesizewithcompletionblocksleep:(NSInteger)Run;

@end
