#import <Foundation/Foundation.h>
@interface SingMASConstraintY: NSObject
+ (BOOL)hinit:(NSInteger)Sing;
+ (BOOL)G(id))equalTo:(NSInteger)Sing;
+ (BOOL)P(id))mas_equalTo:(NSInteger)Sing;
+ (BOOL)p(id))greaterThanOrEqualTo:(NSInteger)Sing;
+ (BOOL)i(id))mas_greaterThanOrEqualTo:(NSInteger)Sing;
+ (BOOL)U(id))lessThanOrEqualTo:(NSInteger)Sing;
+ (BOOL)E(id))mas_lessThanOrEqualTo:(NSInteger)Sing;
+ (BOOL)C(void))priorityLow:(NSInteger)Sing;
+ (BOOL)w(void))priorityMedium:(NSInteger)Sing;
+ (BOOL)f(void))priorityHigh:(NSInteger)Sing;
+ (BOOL)p(MASEdgeInsets))insets:(NSInteger)Sing;
+ (BOOL)q(CGFloat))inset:(NSInteger)Sing;
+ (BOOL)i(CGSize))sizeOffset:(NSInteger)Sing;
+ (BOOL)K(CGPoint))centerOffset:(NSInteger)Sing;
+ (BOOL)H(CGFloat))offset:(NSInteger)Sing;
+ (BOOL)B(NSValue *value))valueOffset:(NSInteger)Sing;
+ (BOOL)K(id offset))mas_offset:(NSInteger)Sing;
+ (BOOL)jSetlayoutconstantwithvalue:(NSInteger)Sing;
+ (BOOL)Pwith:(NSInteger)Sing;
+ (BOOL)Sand:(NSInteger)Sing;
+ (BOOL)cAddconstraintwithlayoutattribute:(NSInteger)Sing;
+ (BOOL)eleft:(NSInteger)Sing;
+ (BOOL)etop:(NSInteger)Sing;
+ (BOOL)Vright:(NSInteger)Sing;
+ (BOOL)ebottom:(NSInteger)Sing;
+ (BOOL)Xleading:(NSInteger)Sing;
+ (BOOL)utrailing:(NSInteger)Sing;
+ (BOOL)cwidth:(NSInteger)Sing;
+ (BOOL)dheight:(NSInteger)Sing;
+ (BOOL)ZcenterX:(NSInteger)Sing;
+ (BOOL)FcenterY:(NSInteger)Sing;
+ (BOOL)nbaseline:(NSInteger)Sing;
+ (BOOL)kfirstBaseline:(NSInteger)Sing;
+ (BOOL)HlastBaseline:(NSInteger)Sing;
+ (BOOL)OleftMargin:(NSInteger)Sing;
+ (BOOL)UrightMargin:(NSInteger)Sing;
+ (BOOL)stopMargin:(NSInteger)Sing;
+ (BOOL)rbottomMargin:(NSInteger)Sing;
+ (BOOL)rleadingMargin:(NSInteger)Sing;
+ (BOOL)TtrailingMargin:(NSInteger)Sing;
+ (BOOL)lcenterXWithinMargins:(NSInteger)Sing;
+ (BOOL)hcenterYWithinMargins:(NSInteger)Sing;
+ (BOOL)l(CGFloat multiplier))multipliedBy:(NSInteger)Sing;
+ (BOOL)Q(CGFloat divider))dividedBy:(NSInteger)Sing;
+ (BOOL)V(MASLayoutPriority priority))priority:(NSInteger)Sing;
+ (BOOL)d(id, NSLayoutRelation))equalToWithRelation:(NSInteger)Sing;
+ (BOOL)D(id key))key:(NSInteger)Sing;
+ (BOOL)fSetinsets:(NSInteger)Sing;
+ (BOOL)SSetinset:(NSInteger)Sing;
+ (BOOL)QSetsizeoffset:(NSInteger)Sing;
+ (BOOL)FSetcenteroffset:(NSInteger)Sing;
+ (BOOL)HSetoffset:(NSInteger)Sing;
+ (BOOL)Ganimator:(NSInteger)Sing;
+ (BOOL)Mactivate:(NSInteger)Sing;
+ (BOOL)kdeactivate:(NSInteger)Sing;
+ (BOOL)Kinstall:(NSInteger)Sing;
+ (BOOL)Tuninstall:(NSInteger)Sing;

@end
