#import <Foundation/Foundation.h>
@interface SingMBProgressHUDx: NSObject
+ (BOOL)nShowhudaddedtoanimatedrun:(NSInteger)Sing;
+ (BOOL)uHidehudforviewanimatedrun:(NSInteger)Sing;
+ (BOOL)qHudforviewrun:(NSInteger)Sing;
+ (BOOL)fCommoninitrun:(NSInteger)Sing;
+ (BOOL)JInitwithframerun:(NSInteger)Sing;
+ (BOOL)xInitwithcoderrun:(NSInteger)Sing;
+ (BOOL)qInitwithviewrun:(NSInteger)Sing;
+ (BOOL)eDeallocrun:(NSInteger)Sing;
+ (BOOL)VShowanimatedrun:(NSInteger)Sing;
+ (BOOL)RHideanimatedrun:(NSInteger)Sing;
+ (BOOL)dHideanimatedafterdelayrun:(NSInteger)Sing;
+ (BOOL)gHandlegracetimerrun:(NSInteger)Sing;
+ (BOOL)GHandleminshowtimerrun:(NSInteger)Sing;
+ (BOOL)xHandlehidetimerrun:(NSInteger)Sing;
+ (BOOL)GDidmovetosuperviewrun:(NSInteger)Sing;
+ (BOOL)uShowusinganimationrun:(NSInteger)Sing;
+ (BOOL)bHideusinganimationrun:(NSInteger)Sing;
+ (BOOL)UAnimateinwithtypecompletionrun:(NSInteger)Sing;
+ (BOOL)MDonerun:(NSInteger)Sing;
+ (BOOL)bSetupviewsrun:(NSInteger)Sing;
+ (BOOL)gUpdateindicatorsrun:(NSInteger)Sing;
+ (BOOL)PUpdateviewsforcolorrun:(NSInteger)Sing;
+ (BOOL)qUpdatebezelmotioneffectsrun:(NSInteger)Sing;
+ (BOOL)fUpdateconstraintsrun:(NSInteger)Sing;
+ (BOOL)eLayoutsubviewsrun:(NSInteger)Sing;
+ (BOOL)oUpdatepaddingconstraintsrun:(NSInteger)Sing;
+ (BOOL)FApplyprioritytoconstraintsrun:(NSInteger)Sing;
+ (BOOL)xSetmoderun:(NSInteger)Sing;
+ (BOOL)QSetcustomviewrun:(NSInteger)Sing;
+ (BOOL)DSetoffsetrun:(NSInteger)Sing;
+ (BOOL)BSetmarginrun:(NSInteger)Sing;
+ (BOOL)uSetminsizerun:(NSInteger)Sing;
+ (BOOL)zSetsquarerun:(NSInteger)Sing;
+ (BOOL)sSetprogressobjectdisplaylinkrun:(NSInteger)Sing;
+ (BOOL)pSetprogressobjectrun:(NSInteger)Sing;
+ (BOOL)FSetprogressrun:(NSInteger)Sing;
+ (BOOL)uSetcontentcolorrun:(NSInteger)Sing;
+ (BOOL)OSetdefaultmotioneffectsenabledrun:(NSInteger)Sing;
+ (BOOL)OSetnsprogressdisplaylinkenabledrun:(NSInteger)Sing;
+ (BOOL)SUpdateprogressfromprogressobjectrun:(NSInteger)Sing;
+ (BOOL)mRegisterfornotificationsrun:(NSInteger)Sing;
+ (BOOL)OUnregisterfromnotificationsrun:(NSInteger)Sing;
+ (BOOL)SStatusbarorientationdidchangerun:(NSInteger)Sing;
+ (BOOL)sUpdateforcurrentorientationanimatedrun:(NSInteger)Sing;

@end
