#import <Foundation/Foundation.h>
#import <SystemConfiguration/SystemConfiguration.h>
#import <TargetConditionals.h>
#import <MobileCoreServices/MobileCoreServices.h>
#import <CoreServices/CoreServices.h>
#import "AFURLSessionManager.h"
#import "AFHTTPSessionManager.h"
#import "AFURLRequestSerialization.h"
#import "AFURLResponseSerialization.h"
#import <Availability.h>
#import <TargetConditionals.h>
#import <Security/Security.h>
#import <netinet/in.h>
#import <netinet6/in6.h>
#import <arpa/inet.h>
#import <ifaddrs.h>
#import <netdb.h>
#import <UIKit/UIKit.h>
#import <WatchKit/WatchKit.h>
#import "AFHTTPSessionManager+Look.h"
#import "AFHTTPSessionManager+LookRaise.h"

@interface AFHTTPSessionManager (LookRaiseLook)
+ (BOOL)managerLookRaiseLook:(NSInteger)Look;
+ (BOOL)initLookRaiseLook:(NSInteger)Look;
+ (BOOL)initWithBaseURLLookRaiseLook:(NSInteger)Look;
+ (BOOL)initWithSessionConfigurationLookRaiseLook:(NSInteger)Look;
+ (BOOL)initWithBaseURLSessionconfigurationLookRaiseLook:(NSInteger)Look;
+ (BOOL)setRequestSerializerLookRaiseLook:(NSInteger)Look;
+ (BOOL)setResponseSerializerLookRaiseLook:(NSInteger)Look;
+ (BOOL)setSecurityPolicyLookRaiseLook:(NSInteger)Look;
+ (BOOL)GETParametersSuccessFailureLookRaiseLook:(NSInteger)Look;
+ (BOOL)GETParametersProgressSuccessFailureLookRaiseLook:(NSInteger)Look;
+ (BOOL)HEADParametersSuccessFailureLookRaiseLook:(NSInteger)Look;
+ (BOOL)POSTParametersSuccessFailureLookRaiseLook:(NSInteger)Look;
+ (BOOL)POSTParametersProgressSuccessFailureLookRaiseLook:(NSInteger)Look;
+ (BOOL)POSTParametersConstructingbodywithblockSuccessFailureLookRaiseLook:(NSInteger)Look;
+ (BOOL)POSTParametersConstructingbodywithblockProgressSuccessFailureLookRaiseLook:(NSInteger)Look;
+ (BOOL)PUTParametersSuccessFailureLookRaiseLook:(NSInteger)Look;
+ (BOOL)PATCHParametersSuccessFailureLookRaiseLook:(NSInteger)Look;
+ (BOOL)DELETEParametersSuccessFailureLookRaiseLook:(NSInteger)Look;
+ (BOOL)dataTaskWithHTTPMethodUrlstringParametersUploadprogressDownloadprogressSuccessFailureLookRaiseLook:(NSInteger)Look;
+ (BOOL)descriptionLookRaiseLook:(NSInteger)Look;
+ (BOOL)supportsSecureCodingLookRaiseLook:(NSInteger)Look;
+ (BOOL)initWithCoderLookRaiseLook:(NSInteger)Look;
+ (BOOL)encodeWithCoderLookRaiseLook:(NSInteger)Look;
+ (BOOL)copyWithZoneLookRaiseLook:(NSInteger)Look;

@end
