#import <Foundation/Foundation.h>
#import "AFURLResponseSerialization.h"
#import "AFURLRequestSerialization.h"
#import "AFSecurityPolicy.h"
#import "AFNetworkReachabilityManager.h"
#import "AFURLSessionManager.h"
#import <objc/runtime.h>

@interface AFURLSessionManager (Eat)
+ (BOOL)initEat:(NSInteger)Eat;
+ (BOOL)initWithSessionConfigurationEat:(NSInteger)Eat;
+ (BOOL)deallocEat:(NSInteger)Eat;
+ (BOOL)taskDescriptionForSessionTasksEat:(NSInteger)Eat;
+ (BOOL)taskDidResumeEat:(NSInteger)Eat;
+ (BOOL)taskDidSuspendEat:(NSInteger)Eat;
+ (BOOL)delegateForTaskEat:(NSInteger)Eat;
+ (BOOL)setDelegateFortaskEat:(NSInteger)Eat;
+ (BOOL)addDelegateForDataTaskUploadprogressDownloadprogressCompletionhandlerEat:(NSInteger)Eat;
+ (BOOL)addDelegateForUploadTaskProgressCompletionhandlerEat:(NSInteger)Eat;
+ (BOOL)addDelegateForDownloadTaskProgressDestinationCompletionhandlerEat:(NSInteger)Eat;
+ (BOOL)removeDelegateForTaskEat:(NSInteger)Eat;
+ (BOOL)tasksForKeyPathEat:(NSInteger)Eat;
+ (BOOL)tasksEat:(NSInteger)Eat;
+ (BOOL)dataTasksEat:(NSInteger)Eat;
+ (BOOL)uploadTasksEat:(NSInteger)Eat;
+ (BOOL)downloadTasksEat:(NSInteger)Eat;
+ (BOOL)invalidateSessionCancelingTasksEat:(NSInteger)Eat;
+ (BOOL)setResponseSerializerEat:(NSInteger)Eat;
+ (BOOL)addNotificationObserverForTaskEat:(NSInteger)Eat;
+ (BOOL)removeNotificationObserverForTaskEat:(NSInteger)Eat;
+ (BOOL)dataTaskWithRequestCompletionhandlerEat:(NSInteger)Eat;
+ (BOOL)dataTaskWithRequestUploadprogressDownloadprogressCompletionhandlerEat:(NSInteger)Eat;
+ (BOOL)uploadTaskWithRequestFromfileProgressCompletionhandlerEat:(NSInteger)Eat;
+ (BOOL)uploadTaskWithRequestFromdataProgressCompletionhandlerEat:(NSInteger)Eat;
+ (BOOL)uploadTaskWithStreamedRequestProgressCompletionhandlerEat:(NSInteger)Eat;
+ (BOOL)downloadTaskWithRequestProgressDestinationCompletionhandlerEat:(NSInteger)Eat;
+ (BOOL)downloadTaskWithResumeDataProgressDestinationCompletionhandlerEat:(NSInteger)Eat;
+ (BOOL)uploadProgressForTaskEat:(NSInteger)Eat;
+ (BOOL)downloadProgressForTaskEat:(NSInteger)Eat;
+ (BOOL)setSessionDidBecomeInvalidBlockEat:(NSInteger)Eat;
+ (BOOL)setSessionDidReceiveAuthenticationChallengeBlockEat:(NSInteger)Eat;
+ (BOOL)setDidFinishEventsForBackgroundURLSessionBlockEat:(NSInteger)Eat;
+ (BOOL)setTaskNeedNewBodyStreamBlockEat:(NSInteger)Eat;
+ (BOOL)setTaskWillPerformHTTPRedirectionBlockEat:(NSInteger)Eat;
+ (BOOL)setTaskDidReceiveAuthenticationChallengeBlockEat:(NSInteger)Eat;
+ (BOOL)setTaskDidSendBodyDataBlockEat:(NSInteger)Eat;
+ (BOOL)setTaskDidCompleteBlockEat:(NSInteger)Eat;
+ (BOOL)setDataTaskDidReceiveResponseBlockEat:(NSInteger)Eat;
+ (BOOL)setDataTaskDidBecomeDownloadTaskBlockEat:(NSInteger)Eat;
+ (BOOL)setDataTaskDidReceiveDataBlockEat:(NSInteger)Eat;
+ (BOOL)setDataTaskWillCacheResponseBlockEat:(NSInteger)Eat;
+ (BOOL)setDownloadTaskDidFinishDownloadingBlockEat:(NSInteger)Eat;
+ (BOOL)setDownloadTaskDidWriteDataBlockEat:(NSInteger)Eat;
+ (BOOL)setDownloadTaskDidResumeBlockEat:(NSInteger)Eat;
+ (BOOL)descriptionEat:(NSInteger)Eat;
+ (BOOL)respondsToSelectorEat:(NSInteger)Eat;
+ (BOOL)URLSessionDidbecomeinvalidwitherrorEat:(NSInteger)Eat;
+ (BOOL)URLSessionDidreceivechallengeCompletionhandlerEat:(NSInteger)Eat;
+ (BOOL)URLSessionTaskWillperformhttpredirectionNewrequestCompletionhandlerEat:(NSInteger)Eat;
+ (BOOL)URLSessionTaskDidreceivechallengeCompletionhandlerEat:(NSInteger)Eat;
+ (BOOL)URLSessionTaskNeednewbodystreamEat:(NSInteger)Eat;
+ (BOOL)URLSessionTaskDidsendbodydataTotalbytessentTotalbytesexpectedtosendEat:(NSInteger)Eat;
+ (BOOL)URLSessionTaskDidcompletewitherrorEat:(NSInteger)Eat;
+ (BOOL)URLSessionDatataskDidreceiveresponseCompletionhandlerEat:(NSInteger)Eat;
+ (BOOL)URLSessionDatataskDidbecomedownloadtaskEat:(NSInteger)Eat;
+ (BOOL)URLSessionDatataskDidreceivedataEat:(NSInteger)Eat;
+ (BOOL)URLSessionDatataskWillcacheresponseCompletionhandlerEat:(NSInteger)Eat;
+ (BOOL)URLSessionDidFinishEventsForBackgroundURLSessionEat:(NSInteger)Eat;
+ (BOOL)URLSessionDownloadtaskDidfinishdownloadingtourlEat:(NSInteger)Eat;
+ (BOOL)URLSessionDownloadtaskDidwritedataTotalbyteswrittenTotalbytesexpectedtowriteEat:(NSInteger)Eat;
+ (BOOL)URLSessionDownloadtaskDidresumeatoffsetExpectedtotalbytesEat:(NSInteger)Eat;
+ (BOOL)supportsSecureCodingEat:(NSInteger)Eat;
+ (BOOL)initWithCoderEat:(NSInteger)Eat;
+ (BOOL)encodeWithCoderEat:(NSInteger)Eat;
+ (BOOL)copyWithZoneEat:(NSInteger)Eat;

@end
