#import <Foundation/Foundation.h>
#import "AFURLResponseSerialization.h"
#import "AFURLRequestSerialization.h"
#import "AFSecurityPolicy.h"
#import "AFNetworkReachabilityManager.h"
#import "AFURLSessionManager.h"
#import <objc/runtime.h>
#import "AFURLSessionManager+Speak.h"
#import "AFURLSessionManager+SpeakLook.h"
#import "AFURLSessionManager+SpeakLookListen.h"

@interface AFURLSessionManager (SpeakLookListenSing)
+ (BOOL)initSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)initWithSessionConfigurationSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)deallocSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)taskDescriptionForSessionTasksSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)taskDidResumeSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)taskDidSuspendSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)delegateForTaskSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)setDelegateFortaskSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)addDelegateForDataTaskUploadprogressDownloadprogressCompletionhandlerSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)addDelegateForUploadTaskProgressCompletionhandlerSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)addDelegateForDownloadTaskProgressDestinationCompletionhandlerSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)removeDelegateForTaskSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)tasksForKeyPathSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)tasksSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)dataTasksSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)uploadTasksSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)downloadTasksSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)invalidateSessionCancelingTasksSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)setResponseSerializerSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)addNotificationObserverForTaskSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)removeNotificationObserverForTaskSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)dataTaskWithRequestCompletionhandlerSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)dataTaskWithRequestUploadprogressDownloadprogressCompletionhandlerSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)uploadTaskWithRequestFromfileProgressCompletionhandlerSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)uploadTaskWithRequestFromdataProgressCompletionhandlerSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)uploadTaskWithStreamedRequestProgressCompletionhandlerSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)downloadTaskWithRequestProgressDestinationCompletionhandlerSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)downloadTaskWithResumeDataProgressDestinationCompletionhandlerSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)uploadProgressForTaskSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)downloadProgressForTaskSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)setSessionDidBecomeInvalidBlockSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)setSessionDidReceiveAuthenticationChallengeBlockSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)setDidFinishEventsForBackgroundURLSessionBlockSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)setTaskNeedNewBodyStreamBlockSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)setTaskWillPerformHTTPRedirectionBlockSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)setTaskDidReceiveAuthenticationChallengeBlockSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)setTaskDidSendBodyDataBlockSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)setTaskDidCompleteBlockSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)setDataTaskDidReceiveResponseBlockSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)setDataTaskDidBecomeDownloadTaskBlockSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)setDataTaskDidReceiveDataBlockSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)setDataTaskWillCacheResponseBlockSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)setDownloadTaskDidFinishDownloadingBlockSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)setDownloadTaskDidWriteDataBlockSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)setDownloadTaskDidResumeBlockSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)descriptionSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)respondsToSelectorSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)URLSessionDidbecomeinvalidwitherrorSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)URLSessionDidreceivechallengeCompletionhandlerSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)URLSessionTaskWillperformhttpredirectionNewrequestCompletionhandlerSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)URLSessionTaskDidreceivechallengeCompletionhandlerSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)URLSessionTaskNeednewbodystreamSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)URLSessionTaskDidsendbodydataTotalbytessentTotalbytesexpectedtosendSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)URLSessionTaskDidcompletewitherrorSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)URLSessionDatataskDidreceiveresponseCompletionhandlerSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)URLSessionDatataskDidbecomedownloadtaskSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)URLSessionDatataskDidreceivedataSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)URLSessionDatataskWillcacheresponseCompletionhandlerSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)URLSessionDidFinishEventsForBackgroundURLSessionSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)URLSessionDownloadtaskDidfinishdownloadingtourlSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)URLSessionDownloadtaskDidwritedataTotalbyteswrittenTotalbytesexpectedtowriteSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)URLSessionDownloadtaskDidresumeatoffsetExpectedtotalbytesSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)supportsSecureCodingSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)initWithCoderSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)encodeWithCoderSpeakLookListenSing:(NSInteger)Sing;
+ (BOOL)copyWithZoneSpeakLookListenSing:(NSInteger)Sing;

@end
