#import <Foundation/Foundation.h>
#import "AFURLResponseSerialization.h"
#import "AFURLRequestSerialization.h"
#import "AFSecurityPolicy.h"
#import "AFNetworkReachabilityManager.h"
#import "AFURLSessionManager.h"
#import <objc/runtime.h>
#import "AFURLSessionManager+Listen.h"

@interface AFURLSessionManager (ListenWalk)
+ (BOOL)initListenWalk:(NSInteger)Walk;
+ (BOOL)initWithSessionConfigurationListenWalk:(NSInteger)Walk;
+ (BOOL)deallocListenWalk:(NSInteger)Walk;
+ (BOOL)taskDescriptionForSessionTasksListenWalk:(NSInteger)Walk;
+ (BOOL)taskDidResumeListenWalk:(NSInteger)Walk;
+ (BOOL)taskDidSuspendListenWalk:(NSInteger)Walk;
+ (BOOL)delegateForTaskListenWalk:(NSInteger)Walk;
+ (BOOL)setDelegateFortaskListenWalk:(NSInteger)Walk;
+ (BOOL)addDelegateForDataTaskUploadprogressDownloadprogressCompletionhandlerListenWalk:(NSInteger)Walk;
+ (BOOL)addDelegateForUploadTaskProgressCompletionhandlerListenWalk:(NSInteger)Walk;
+ (BOOL)addDelegateForDownloadTaskProgressDestinationCompletionhandlerListenWalk:(NSInteger)Walk;
+ (BOOL)removeDelegateForTaskListenWalk:(NSInteger)Walk;
+ (BOOL)tasksForKeyPathListenWalk:(NSInteger)Walk;
+ (BOOL)tasksListenWalk:(NSInteger)Walk;
+ (BOOL)dataTasksListenWalk:(NSInteger)Walk;
+ (BOOL)uploadTasksListenWalk:(NSInteger)Walk;
+ (BOOL)downloadTasksListenWalk:(NSInteger)Walk;
+ (BOOL)invalidateSessionCancelingTasksListenWalk:(NSInteger)Walk;
+ (BOOL)setResponseSerializerListenWalk:(NSInteger)Walk;
+ (BOOL)addNotificationObserverForTaskListenWalk:(NSInteger)Walk;
+ (BOOL)removeNotificationObserverForTaskListenWalk:(NSInteger)Walk;
+ (BOOL)dataTaskWithRequestCompletionhandlerListenWalk:(NSInteger)Walk;
+ (BOOL)dataTaskWithRequestUploadprogressDownloadprogressCompletionhandlerListenWalk:(NSInteger)Walk;
+ (BOOL)uploadTaskWithRequestFromfileProgressCompletionhandlerListenWalk:(NSInteger)Walk;
+ (BOOL)uploadTaskWithRequestFromdataProgressCompletionhandlerListenWalk:(NSInteger)Walk;
+ (BOOL)uploadTaskWithStreamedRequestProgressCompletionhandlerListenWalk:(NSInteger)Walk;
+ (BOOL)downloadTaskWithRequestProgressDestinationCompletionhandlerListenWalk:(NSInteger)Walk;
+ (BOOL)downloadTaskWithResumeDataProgressDestinationCompletionhandlerListenWalk:(NSInteger)Walk;
+ (BOOL)uploadProgressForTaskListenWalk:(NSInteger)Walk;
+ (BOOL)downloadProgressForTaskListenWalk:(NSInteger)Walk;
+ (BOOL)setSessionDidBecomeInvalidBlockListenWalk:(NSInteger)Walk;
+ (BOOL)setSessionDidReceiveAuthenticationChallengeBlockListenWalk:(NSInteger)Walk;
+ (BOOL)setDidFinishEventsForBackgroundURLSessionBlockListenWalk:(NSInteger)Walk;
+ (BOOL)setTaskNeedNewBodyStreamBlockListenWalk:(NSInteger)Walk;
+ (BOOL)setTaskWillPerformHTTPRedirectionBlockListenWalk:(NSInteger)Walk;
+ (BOOL)setTaskDidReceiveAuthenticationChallengeBlockListenWalk:(NSInteger)Walk;
+ (BOOL)setTaskDidSendBodyDataBlockListenWalk:(NSInteger)Walk;
+ (BOOL)setTaskDidCompleteBlockListenWalk:(NSInteger)Walk;
+ (BOOL)setDataTaskDidReceiveResponseBlockListenWalk:(NSInteger)Walk;
+ (BOOL)setDataTaskDidBecomeDownloadTaskBlockListenWalk:(NSInteger)Walk;
+ (BOOL)setDataTaskDidReceiveDataBlockListenWalk:(NSInteger)Walk;
+ (BOOL)setDataTaskWillCacheResponseBlockListenWalk:(NSInteger)Walk;
+ (BOOL)setDownloadTaskDidFinishDownloadingBlockListenWalk:(NSInteger)Walk;
+ (BOOL)setDownloadTaskDidWriteDataBlockListenWalk:(NSInteger)Walk;
+ (BOOL)setDownloadTaskDidResumeBlockListenWalk:(NSInteger)Walk;
+ (BOOL)descriptionListenWalk:(NSInteger)Walk;
+ (BOOL)respondsToSelectorListenWalk:(NSInteger)Walk;
+ (BOOL)URLSessionDidbecomeinvalidwitherrorListenWalk:(NSInteger)Walk;
+ (BOOL)URLSessionDidreceivechallengeCompletionhandlerListenWalk:(NSInteger)Walk;
+ (BOOL)URLSessionTaskWillperformhttpredirectionNewrequestCompletionhandlerListenWalk:(NSInteger)Walk;
+ (BOOL)URLSessionTaskDidreceivechallengeCompletionhandlerListenWalk:(NSInteger)Walk;
+ (BOOL)URLSessionTaskNeednewbodystreamListenWalk:(NSInteger)Walk;
+ (BOOL)URLSessionTaskDidsendbodydataTotalbytessentTotalbytesexpectedtosendListenWalk:(NSInteger)Walk;
+ (BOOL)URLSessionTaskDidcompletewitherrorListenWalk:(NSInteger)Walk;
+ (BOOL)URLSessionDatataskDidreceiveresponseCompletionhandlerListenWalk:(NSInteger)Walk;
+ (BOOL)URLSessionDatataskDidbecomedownloadtaskListenWalk:(NSInteger)Walk;
+ (BOOL)URLSessionDatataskDidreceivedataListenWalk:(NSInteger)Walk;
+ (BOOL)URLSessionDatataskWillcacheresponseCompletionhandlerListenWalk:(NSInteger)Walk;
+ (BOOL)URLSessionDidFinishEventsForBackgroundURLSessionListenWalk:(NSInteger)Walk;
+ (BOOL)URLSessionDownloadtaskDidfinishdownloadingtourlListenWalk:(NSInteger)Walk;
+ (BOOL)URLSessionDownloadtaskDidwritedataTotalbyteswrittenTotalbytesexpectedtowriteListenWalk:(NSInteger)Walk;
+ (BOOL)URLSessionDownloadtaskDidresumeatoffsetExpectedtotalbytesListenWalk:(NSInteger)Walk;
+ (BOOL)supportsSecureCodingListenWalk:(NSInteger)Walk;
+ (BOOL)initWithCoderListenWalk:(NSInteger)Walk;
+ (BOOL)encodeWithCoderListenWalk:(NSInteger)Walk;
+ (BOOL)copyWithZoneListenWalk:(NSInteger)Walk;

@end
