#import <Foundation/Foundation.h>
#import "AFURLResponseSerialization.h"
#import "AFURLRequestSerialization.h"
#import "AFSecurityPolicy.h"
#import "AFNetworkReachabilityManager.h"
#import "AFURLSessionManager.h"
#import <objc/runtime.h>
#import "AFURLSessionManager+Speak.h"
#import "AFURLSessionManager+SpeakRun.h"

@interface AFURLSessionManager (SpeakRunSing)
+ (BOOL)initSpeakRunSing:(NSInteger)Sing;
+ (BOOL)initWithSessionConfigurationSpeakRunSing:(NSInteger)Sing;
+ (BOOL)deallocSpeakRunSing:(NSInteger)Sing;
+ (BOOL)taskDescriptionForSessionTasksSpeakRunSing:(NSInteger)Sing;
+ (BOOL)taskDidResumeSpeakRunSing:(NSInteger)Sing;
+ (BOOL)taskDidSuspendSpeakRunSing:(NSInteger)Sing;
+ (BOOL)delegateForTaskSpeakRunSing:(NSInteger)Sing;
+ (BOOL)setDelegateFortaskSpeakRunSing:(NSInteger)Sing;
+ (BOOL)addDelegateForDataTaskUploadprogressDownloadprogressCompletionhandlerSpeakRunSing:(NSInteger)Sing;
+ (BOOL)addDelegateForUploadTaskProgressCompletionhandlerSpeakRunSing:(NSInteger)Sing;
+ (BOOL)addDelegateForDownloadTaskProgressDestinationCompletionhandlerSpeakRunSing:(NSInteger)Sing;
+ (BOOL)removeDelegateForTaskSpeakRunSing:(NSInteger)Sing;
+ (BOOL)tasksForKeyPathSpeakRunSing:(NSInteger)Sing;
+ (BOOL)tasksSpeakRunSing:(NSInteger)Sing;
+ (BOOL)dataTasksSpeakRunSing:(NSInteger)Sing;
+ (BOOL)uploadTasksSpeakRunSing:(NSInteger)Sing;
+ (BOOL)downloadTasksSpeakRunSing:(NSInteger)Sing;
+ (BOOL)invalidateSessionCancelingTasksSpeakRunSing:(NSInteger)Sing;
+ (BOOL)setResponseSerializerSpeakRunSing:(NSInteger)Sing;
+ (BOOL)addNotificationObserverForTaskSpeakRunSing:(NSInteger)Sing;
+ (BOOL)removeNotificationObserverForTaskSpeakRunSing:(NSInteger)Sing;
+ (BOOL)dataTaskWithRequestCompletionhandlerSpeakRunSing:(NSInteger)Sing;
+ (BOOL)dataTaskWithRequestUploadprogressDownloadprogressCompletionhandlerSpeakRunSing:(NSInteger)Sing;
+ (BOOL)uploadTaskWithRequestFromfileProgressCompletionhandlerSpeakRunSing:(NSInteger)Sing;
+ (BOOL)uploadTaskWithRequestFromdataProgressCompletionhandlerSpeakRunSing:(NSInteger)Sing;
+ (BOOL)uploadTaskWithStreamedRequestProgressCompletionhandlerSpeakRunSing:(NSInteger)Sing;
+ (BOOL)downloadTaskWithRequestProgressDestinationCompletionhandlerSpeakRunSing:(NSInteger)Sing;
+ (BOOL)downloadTaskWithResumeDataProgressDestinationCompletionhandlerSpeakRunSing:(NSInteger)Sing;
+ (BOOL)uploadProgressForTaskSpeakRunSing:(NSInteger)Sing;
+ (BOOL)downloadProgressForTaskSpeakRunSing:(NSInteger)Sing;
+ (BOOL)setSessionDidBecomeInvalidBlockSpeakRunSing:(NSInteger)Sing;
+ (BOOL)setSessionDidReceiveAuthenticationChallengeBlockSpeakRunSing:(NSInteger)Sing;
+ (BOOL)setDidFinishEventsForBackgroundURLSessionBlockSpeakRunSing:(NSInteger)Sing;
+ (BOOL)setTaskNeedNewBodyStreamBlockSpeakRunSing:(NSInteger)Sing;
+ (BOOL)setTaskWillPerformHTTPRedirectionBlockSpeakRunSing:(NSInteger)Sing;
+ (BOOL)setTaskDidReceiveAuthenticationChallengeBlockSpeakRunSing:(NSInteger)Sing;
+ (BOOL)setTaskDidSendBodyDataBlockSpeakRunSing:(NSInteger)Sing;
+ (BOOL)setTaskDidCompleteBlockSpeakRunSing:(NSInteger)Sing;
+ (BOOL)setDataTaskDidReceiveResponseBlockSpeakRunSing:(NSInteger)Sing;
+ (BOOL)setDataTaskDidBecomeDownloadTaskBlockSpeakRunSing:(NSInteger)Sing;
+ (BOOL)setDataTaskDidReceiveDataBlockSpeakRunSing:(NSInteger)Sing;
+ (BOOL)setDataTaskWillCacheResponseBlockSpeakRunSing:(NSInteger)Sing;
+ (BOOL)setDownloadTaskDidFinishDownloadingBlockSpeakRunSing:(NSInteger)Sing;
+ (BOOL)setDownloadTaskDidWriteDataBlockSpeakRunSing:(NSInteger)Sing;
+ (BOOL)setDownloadTaskDidResumeBlockSpeakRunSing:(NSInteger)Sing;
+ (BOOL)descriptionSpeakRunSing:(NSInteger)Sing;
+ (BOOL)respondsToSelectorSpeakRunSing:(NSInteger)Sing;
+ (BOOL)URLSessionDidbecomeinvalidwitherrorSpeakRunSing:(NSInteger)Sing;
+ (BOOL)URLSessionDidreceivechallengeCompletionhandlerSpeakRunSing:(NSInteger)Sing;
+ (BOOL)URLSessionTaskWillperformhttpredirectionNewrequestCompletionhandlerSpeakRunSing:(NSInteger)Sing;
+ (BOOL)URLSessionTaskDidreceivechallengeCompletionhandlerSpeakRunSing:(NSInteger)Sing;
+ (BOOL)URLSessionTaskNeednewbodystreamSpeakRunSing:(NSInteger)Sing;
+ (BOOL)URLSessionTaskDidsendbodydataTotalbytessentTotalbytesexpectedtosendSpeakRunSing:(NSInteger)Sing;
+ (BOOL)URLSessionTaskDidcompletewitherrorSpeakRunSing:(NSInteger)Sing;
+ (BOOL)URLSessionDatataskDidreceiveresponseCompletionhandlerSpeakRunSing:(NSInteger)Sing;
+ (BOOL)URLSessionDatataskDidbecomedownloadtaskSpeakRunSing:(NSInteger)Sing;
+ (BOOL)URLSessionDatataskDidreceivedataSpeakRunSing:(NSInteger)Sing;
+ (BOOL)URLSessionDatataskWillcacheresponseCompletionhandlerSpeakRunSing:(NSInteger)Sing;
+ (BOOL)URLSessionDidFinishEventsForBackgroundURLSessionSpeakRunSing:(NSInteger)Sing;
+ (BOOL)URLSessionDownloadtaskDidfinishdownloadingtourlSpeakRunSing:(NSInteger)Sing;
+ (BOOL)URLSessionDownloadtaskDidwritedataTotalbyteswrittenTotalbytesexpectedtowriteSpeakRunSing:(NSInteger)Sing;
+ (BOOL)URLSessionDownloadtaskDidresumeatoffsetExpectedtotalbytesSpeakRunSing:(NSInteger)Sing;
+ (BOOL)supportsSecureCodingSpeakRunSing:(NSInteger)Sing;
+ (BOOL)initWithCoderSpeakRunSing:(NSInteger)Sing;
+ (BOOL)encodeWithCoderSpeakRunSing:(NSInteger)Sing;
+ (BOOL)copyWithZoneSpeakRunSing:(NSInteger)Sing;

@end
