#import <Foundation/Foundation.h>
#import "AFURLResponseSerialization.h"
#import "AFURLRequestSerialization.h"
#import "AFSecurityPolicy.h"
#import "AFNetworkReachabilityManager.h"
#import "AFURLSessionManager.h"
#import <objc/runtime.h>
#import "AFURLSessionManager+Eat.h"

@interface AFURLSessionManager (EatLook)
+ (BOOL)initEatLook:(NSInteger)Look;
+ (BOOL)initWithSessionConfigurationEatLook:(NSInteger)Look;
+ (BOOL)deallocEatLook:(NSInteger)Look;
+ (BOOL)taskDescriptionForSessionTasksEatLook:(NSInteger)Look;
+ (BOOL)taskDidResumeEatLook:(NSInteger)Look;
+ (BOOL)taskDidSuspendEatLook:(NSInteger)Look;
+ (BOOL)delegateForTaskEatLook:(NSInteger)Look;
+ (BOOL)setDelegateFortaskEatLook:(NSInteger)Look;
+ (BOOL)addDelegateForDataTaskUploadprogressDownloadprogressCompletionhandlerEatLook:(NSInteger)Look;
+ (BOOL)addDelegateForUploadTaskProgressCompletionhandlerEatLook:(NSInteger)Look;
+ (BOOL)addDelegateForDownloadTaskProgressDestinationCompletionhandlerEatLook:(NSInteger)Look;
+ (BOOL)removeDelegateForTaskEatLook:(NSInteger)Look;
+ (BOOL)tasksForKeyPathEatLook:(NSInteger)Look;
+ (BOOL)tasksEatLook:(NSInteger)Look;
+ (BOOL)dataTasksEatLook:(NSInteger)Look;
+ (BOOL)uploadTasksEatLook:(NSInteger)Look;
+ (BOOL)downloadTasksEatLook:(NSInteger)Look;
+ (BOOL)invalidateSessionCancelingTasksEatLook:(NSInteger)Look;
+ (BOOL)setResponseSerializerEatLook:(NSInteger)Look;
+ (BOOL)addNotificationObserverForTaskEatLook:(NSInteger)Look;
+ (BOOL)removeNotificationObserverForTaskEatLook:(NSInteger)Look;
+ (BOOL)dataTaskWithRequestCompletionhandlerEatLook:(NSInteger)Look;
+ (BOOL)dataTaskWithRequestUploadprogressDownloadprogressCompletionhandlerEatLook:(NSInteger)Look;
+ (BOOL)uploadTaskWithRequestFromfileProgressCompletionhandlerEatLook:(NSInteger)Look;
+ (BOOL)uploadTaskWithRequestFromdataProgressCompletionhandlerEatLook:(NSInteger)Look;
+ (BOOL)uploadTaskWithStreamedRequestProgressCompletionhandlerEatLook:(NSInteger)Look;
+ (BOOL)downloadTaskWithRequestProgressDestinationCompletionhandlerEatLook:(NSInteger)Look;
+ (BOOL)downloadTaskWithResumeDataProgressDestinationCompletionhandlerEatLook:(NSInteger)Look;
+ (BOOL)uploadProgressForTaskEatLook:(NSInteger)Look;
+ (BOOL)downloadProgressForTaskEatLook:(NSInteger)Look;
+ (BOOL)setSessionDidBecomeInvalidBlockEatLook:(NSInteger)Look;
+ (BOOL)setSessionDidReceiveAuthenticationChallengeBlockEatLook:(NSInteger)Look;
+ (BOOL)setDidFinishEventsForBackgroundURLSessionBlockEatLook:(NSInteger)Look;
+ (BOOL)setTaskNeedNewBodyStreamBlockEatLook:(NSInteger)Look;
+ (BOOL)setTaskWillPerformHTTPRedirectionBlockEatLook:(NSInteger)Look;
+ (BOOL)setTaskDidReceiveAuthenticationChallengeBlockEatLook:(NSInteger)Look;
+ (BOOL)setTaskDidSendBodyDataBlockEatLook:(NSInteger)Look;
+ (BOOL)setTaskDidCompleteBlockEatLook:(NSInteger)Look;
+ (BOOL)setDataTaskDidReceiveResponseBlockEatLook:(NSInteger)Look;
+ (BOOL)setDataTaskDidBecomeDownloadTaskBlockEatLook:(NSInteger)Look;
+ (BOOL)setDataTaskDidReceiveDataBlockEatLook:(NSInteger)Look;
+ (BOOL)setDataTaskWillCacheResponseBlockEatLook:(NSInteger)Look;
+ (BOOL)setDownloadTaskDidFinishDownloadingBlockEatLook:(NSInteger)Look;
+ (BOOL)setDownloadTaskDidWriteDataBlockEatLook:(NSInteger)Look;
+ (BOOL)setDownloadTaskDidResumeBlockEatLook:(NSInteger)Look;
+ (BOOL)descriptionEatLook:(NSInteger)Look;
+ (BOOL)respondsToSelectorEatLook:(NSInteger)Look;
+ (BOOL)URLSessionDidbecomeinvalidwitherrorEatLook:(NSInteger)Look;
+ (BOOL)URLSessionDidreceivechallengeCompletionhandlerEatLook:(NSInteger)Look;
+ (BOOL)URLSessionTaskWillperformhttpredirectionNewrequestCompletionhandlerEatLook:(NSInteger)Look;
+ (BOOL)URLSessionTaskDidreceivechallengeCompletionhandlerEatLook:(NSInteger)Look;
+ (BOOL)URLSessionTaskNeednewbodystreamEatLook:(NSInteger)Look;
+ (BOOL)URLSessionTaskDidsendbodydataTotalbytessentTotalbytesexpectedtosendEatLook:(NSInteger)Look;
+ (BOOL)URLSessionTaskDidcompletewitherrorEatLook:(NSInteger)Look;
+ (BOOL)URLSessionDatataskDidreceiveresponseCompletionhandlerEatLook:(NSInteger)Look;
+ (BOOL)URLSessionDatataskDidbecomedownloadtaskEatLook:(NSInteger)Look;
+ (BOOL)URLSessionDatataskDidreceivedataEatLook:(NSInteger)Look;
+ (BOOL)URLSessionDatataskWillcacheresponseCompletionhandlerEatLook:(NSInteger)Look;
+ (BOOL)URLSessionDidFinishEventsForBackgroundURLSessionEatLook:(NSInteger)Look;
+ (BOOL)URLSessionDownloadtaskDidfinishdownloadingtourlEatLook:(NSInteger)Look;
+ (BOOL)URLSessionDownloadtaskDidwritedataTotalbyteswrittenTotalbytesexpectedtowriteEatLook:(NSInteger)Look;
+ (BOOL)URLSessionDownloadtaskDidresumeatoffsetExpectedtotalbytesEatLook:(NSInteger)Look;
+ (BOOL)supportsSecureCodingEatLook:(NSInteger)Look;
+ (BOOL)initWithCoderEatLook:(NSInteger)Look;
+ (BOOL)encodeWithCoderEatLook:(NSInteger)Look;
+ (BOOL)copyWithZoneEatLook:(NSInteger)Look;

@end
