#import <Foundation/Foundation.h>
#import "AFURLResponseSerialization.h"
#import "AFURLRequestSerialization.h"
#import "AFSecurityPolicy.h"
#import "AFNetworkReachabilityManager.h"
#import "AFURLSessionManager.h"
#import <objc/runtime.h>
#import "AFURLSessionManager+Dance.h"

@interface AFURLSessionManager (DanceRun)
+ (BOOL)initDanceRun:(NSInteger)Run;
+ (BOOL)initWithSessionConfigurationDanceRun:(NSInteger)Run;
+ (BOOL)deallocDanceRun:(NSInteger)Run;
+ (BOOL)taskDescriptionForSessionTasksDanceRun:(NSInteger)Run;
+ (BOOL)taskDidResumeDanceRun:(NSInteger)Run;
+ (BOOL)taskDidSuspendDanceRun:(NSInteger)Run;
+ (BOOL)delegateForTaskDanceRun:(NSInteger)Run;
+ (BOOL)setDelegateFortaskDanceRun:(NSInteger)Run;
+ (BOOL)addDelegateForDataTaskUploadprogressDownloadprogressCompletionhandlerDanceRun:(NSInteger)Run;
+ (BOOL)addDelegateForUploadTaskProgressCompletionhandlerDanceRun:(NSInteger)Run;
+ (BOOL)addDelegateForDownloadTaskProgressDestinationCompletionhandlerDanceRun:(NSInteger)Run;
+ (BOOL)removeDelegateForTaskDanceRun:(NSInteger)Run;
+ (BOOL)tasksForKeyPathDanceRun:(NSInteger)Run;
+ (BOOL)tasksDanceRun:(NSInteger)Run;
+ (BOOL)dataTasksDanceRun:(NSInteger)Run;
+ (BOOL)uploadTasksDanceRun:(NSInteger)Run;
+ (BOOL)downloadTasksDanceRun:(NSInteger)Run;
+ (BOOL)invalidateSessionCancelingTasksDanceRun:(NSInteger)Run;
+ (BOOL)setResponseSerializerDanceRun:(NSInteger)Run;
+ (BOOL)addNotificationObserverForTaskDanceRun:(NSInteger)Run;
+ (BOOL)removeNotificationObserverForTaskDanceRun:(NSInteger)Run;
+ (BOOL)dataTaskWithRequestCompletionhandlerDanceRun:(NSInteger)Run;
+ (BOOL)dataTaskWithRequestUploadprogressDownloadprogressCompletionhandlerDanceRun:(NSInteger)Run;
+ (BOOL)uploadTaskWithRequestFromfileProgressCompletionhandlerDanceRun:(NSInteger)Run;
+ (BOOL)uploadTaskWithRequestFromdataProgressCompletionhandlerDanceRun:(NSInteger)Run;
+ (BOOL)uploadTaskWithStreamedRequestProgressCompletionhandlerDanceRun:(NSInteger)Run;
+ (BOOL)downloadTaskWithRequestProgressDestinationCompletionhandlerDanceRun:(NSInteger)Run;
+ (BOOL)downloadTaskWithResumeDataProgressDestinationCompletionhandlerDanceRun:(NSInteger)Run;
+ (BOOL)uploadProgressForTaskDanceRun:(NSInteger)Run;
+ (BOOL)downloadProgressForTaskDanceRun:(NSInteger)Run;
+ (BOOL)setSessionDidBecomeInvalidBlockDanceRun:(NSInteger)Run;
+ (BOOL)setSessionDidReceiveAuthenticationChallengeBlockDanceRun:(NSInteger)Run;
+ (BOOL)setDidFinishEventsForBackgroundURLSessionBlockDanceRun:(NSInteger)Run;
+ (BOOL)setTaskNeedNewBodyStreamBlockDanceRun:(NSInteger)Run;
+ (BOOL)setTaskWillPerformHTTPRedirectionBlockDanceRun:(NSInteger)Run;
+ (BOOL)setTaskDidReceiveAuthenticationChallengeBlockDanceRun:(NSInteger)Run;
+ (BOOL)setTaskDidSendBodyDataBlockDanceRun:(NSInteger)Run;
+ (BOOL)setTaskDidCompleteBlockDanceRun:(NSInteger)Run;
+ (BOOL)setDataTaskDidReceiveResponseBlockDanceRun:(NSInteger)Run;
+ (BOOL)setDataTaskDidBecomeDownloadTaskBlockDanceRun:(NSInteger)Run;
+ (BOOL)setDataTaskDidReceiveDataBlockDanceRun:(NSInteger)Run;
+ (BOOL)setDataTaskWillCacheResponseBlockDanceRun:(NSInteger)Run;
+ (BOOL)setDownloadTaskDidFinishDownloadingBlockDanceRun:(NSInteger)Run;
+ (BOOL)setDownloadTaskDidWriteDataBlockDanceRun:(NSInteger)Run;
+ (BOOL)setDownloadTaskDidResumeBlockDanceRun:(NSInteger)Run;
+ (BOOL)descriptionDanceRun:(NSInteger)Run;
+ (BOOL)respondsToSelectorDanceRun:(NSInteger)Run;
+ (BOOL)URLSessionDidbecomeinvalidwitherrorDanceRun:(NSInteger)Run;
+ (BOOL)URLSessionDidreceivechallengeCompletionhandlerDanceRun:(NSInteger)Run;
+ (BOOL)URLSessionTaskWillperformhttpredirectionNewrequestCompletionhandlerDanceRun:(NSInteger)Run;
+ (BOOL)URLSessionTaskDidreceivechallengeCompletionhandlerDanceRun:(NSInteger)Run;
+ (BOOL)URLSessionTaskNeednewbodystreamDanceRun:(NSInteger)Run;
+ (BOOL)URLSessionTaskDidsendbodydataTotalbytessentTotalbytesexpectedtosendDanceRun:(NSInteger)Run;
+ (BOOL)URLSessionTaskDidcompletewitherrorDanceRun:(NSInteger)Run;
+ (BOOL)URLSessionDatataskDidreceiveresponseCompletionhandlerDanceRun:(NSInteger)Run;
+ (BOOL)URLSessionDatataskDidbecomedownloadtaskDanceRun:(NSInteger)Run;
+ (BOOL)URLSessionDatataskDidreceivedataDanceRun:(NSInteger)Run;
+ (BOOL)URLSessionDatataskWillcacheresponseCompletionhandlerDanceRun:(NSInteger)Run;
+ (BOOL)URLSessionDidFinishEventsForBackgroundURLSessionDanceRun:(NSInteger)Run;
+ (BOOL)URLSessionDownloadtaskDidfinishdownloadingtourlDanceRun:(NSInteger)Run;
+ (BOOL)URLSessionDownloadtaskDidwritedataTotalbyteswrittenTotalbytesexpectedtowriteDanceRun:(NSInteger)Run;
+ (BOOL)URLSessionDownloadtaskDidresumeatoffsetExpectedtotalbytesDanceRun:(NSInteger)Run;
+ (BOOL)supportsSecureCodingDanceRun:(NSInteger)Run;
+ (BOOL)initWithCoderDanceRun:(NSInteger)Run;
+ (BOOL)encodeWithCoderDanceRun:(NSInteger)Run;
+ (BOOL)copyWithZoneDanceRun:(NSInteger)Run;

@end
