#import <Foundation/Foundation.h>
#import "AFURLResponseSerialization.h"
#import "AFURLRequestSerialization.h"
#import "AFSecurityPolicy.h"
#import "AFNetworkReachabilityManager.h"
#import "AFURLSessionManager.h"
#import <objc/runtime.h>
#import "AFURLSessionManager+Speak.h"

@interface AFURLSessionManager (SpeakRun)
+ (BOOL)initSpeakRun:(NSInteger)Run;
+ (BOOL)initWithSessionConfigurationSpeakRun:(NSInteger)Run;
+ (BOOL)deallocSpeakRun:(NSInteger)Run;
+ (BOOL)taskDescriptionForSessionTasksSpeakRun:(NSInteger)Run;
+ (BOOL)taskDidResumeSpeakRun:(NSInteger)Run;
+ (BOOL)taskDidSuspendSpeakRun:(NSInteger)Run;
+ (BOOL)delegateForTaskSpeakRun:(NSInteger)Run;
+ (BOOL)setDelegateFortaskSpeakRun:(NSInteger)Run;
+ (BOOL)addDelegateForDataTaskUploadprogressDownloadprogressCompletionhandlerSpeakRun:(NSInteger)Run;
+ (BOOL)addDelegateForUploadTaskProgressCompletionhandlerSpeakRun:(NSInteger)Run;
+ (BOOL)addDelegateForDownloadTaskProgressDestinationCompletionhandlerSpeakRun:(NSInteger)Run;
+ (BOOL)removeDelegateForTaskSpeakRun:(NSInteger)Run;
+ (BOOL)tasksForKeyPathSpeakRun:(NSInteger)Run;
+ (BOOL)tasksSpeakRun:(NSInteger)Run;
+ (BOOL)dataTasksSpeakRun:(NSInteger)Run;
+ (BOOL)uploadTasksSpeakRun:(NSInteger)Run;
+ (BOOL)downloadTasksSpeakRun:(NSInteger)Run;
+ (BOOL)invalidateSessionCancelingTasksSpeakRun:(NSInteger)Run;
+ (BOOL)setResponseSerializerSpeakRun:(NSInteger)Run;
+ (BOOL)addNotificationObserverForTaskSpeakRun:(NSInteger)Run;
+ (BOOL)removeNotificationObserverForTaskSpeakRun:(NSInteger)Run;
+ (BOOL)dataTaskWithRequestCompletionhandlerSpeakRun:(NSInteger)Run;
+ (BOOL)dataTaskWithRequestUploadprogressDownloadprogressCompletionhandlerSpeakRun:(NSInteger)Run;
+ (BOOL)uploadTaskWithRequestFromfileProgressCompletionhandlerSpeakRun:(NSInteger)Run;
+ (BOOL)uploadTaskWithRequestFromdataProgressCompletionhandlerSpeakRun:(NSInteger)Run;
+ (BOOL)uploadTaskWithStreamedRequestProgressCompletionhandlerSpeakRun:(NSInteger)Run;
+ (BOOL)downloadTaskWithRequestProgressDestinationCompletionhandlerSpeakRun:(NSInteger)Run;
+ (BOOL)downloadTaskWithResumeDataProgressDestinationCompletionhandlerSpeakRun:(NSInteger)Run;
+ (BOOL)uploadProgressForTaskSpeakRun:(NSInteger)Run;
+ (BOOL)downloadProgressForTaskSpeakRun:(NSInteger)Run;
+ (BOOL)setSessionDidBecomeInvalidBlockSpeakRun:(NSInteger)Run;
+ (BOOL)setSessionDidReceiveAuthenticationChallengeBlockSpeakRun:(NSInteger)Run;
+ (BOOL)setDidFinishEventsForBackgroundURLSessionBlockSpeakRun:(NSInteger)Run;
+ (BOOL)setTaskNeedNewBodyStreamBlockSpeakRun:(NSInteger)Run;
+ (BOOL)setTaskWillPerformHTTPRedirectionBlockSpeakRun:(NSInteger)Run;
+ (BOOL)setTaskDidReceiveAuthenticationChallengeBlockSpeakRun:(NSInteger)Run;
+ (BOOL)setTaskDidSendBodyDataBlockSpeakRun:(NSInteger)Run;
+ (BOOL)setTaskDidCompleteBlockSpeakRun:(NSInteger)Run;
+ (BOOL)setDataTaskDidReceiveResponseBlockSpeakRun:(NSInteger)Run;
+ (BOOL)setDataTaskDidBecomeDownloadTaskBlockSpeakRun:(NSInteger)Run;
+ (BOOL)setDataTaskDidReceiveDataBlockSpeakRun:(NSInteger)Run;
+ (BOOL)setDataTaskWillCacheResponseBlockSpeakRun:(NSInteger)Run;
+ (BOOL)setDownloadTaskDidFinishDownloadingBlockSpeakRun:(NSInteger)Run;
+ (BOOL)setDownloadTaskDidWriteDataBlockSpeakRun:(NSInteger)Run;
+ (BOOL)setDownloadTaskDidResumeBlockSpeakRun:(NSInteger)Run;
+ (BOOL)descriptionSpeakRun:(NSInteger)Run;
+ (BOOL)respondsToSelectorSpeakRun:(NSInteger)Run;
+ (BOOL)URLSessionDidbecomeinvalidwitherrorSpeakRun:(NSInteger)Run;
+ (BOOL)URLSessionDidreceivechallengeCompletionhandlerSpeakRun:(NSInteger)Run;
+ (BOOL)URLSessionTaskWillperformhttpredirectionNewrequestCompletionhandlerSpeakRun:(NSInteger)Run;
+ (BOOL)URLSessionTaskDidreceivechallengeCompletionhandlerSpeakRun:(NSInteger)Run;
+ (BOOL)URLSessionTaskNeednewbodystreamSpeakRun:(NSInteger)Run;
+ (BOOL)URLSessionTaskDidsendbodydataTotalbytessentTotalbytesexpectedtosendSpeakRun:(NSInteger)Run;
+ (BOOL)URLSessionTaskDidcompletewitherrorSpeakRun:(NSInteger)Run;
+ (BOOL)URLSessionDatataskDidreceiveresponseCompletionhandlerSpeakRun:(NSInteger)Run;
+ (BOOL)URLSessionDatataskDidbecomedownloadtaskSpeakRun:(NSInteger)Run;
+ (BOOL)URLSessionDatataskDidreceivedataSpeakRun:(NSInteger)Run;
+ (BOOL)URLSessionDatataskWillcacheresponseCompletionhandlerSpeakRun:(NSInteger)Run;
+ (BOOL)URLSessionDidFinishEventsForBackgroundURLSessionSpeakRun:(NSInteger)Run;
+ (BOOL)URLSessionDownloadtaskDidfinishdownloadingtourlSpeakRun:(NSInteger)Run;
+ (BOOL)URLSessionDownloadtaskDidwritedataTotalbyteswrittenTotalbytesexpectedtowriteSpeakRun:(NSInteger)Run;
+ (BOOL)URLSessionDownloadtaskDidresumeatoffsetExpectedtotalbytesSpeakRun:(NSInteger)Run;
+ (BOOL)supportsSecureCodingSpeakRun:(NSInteger)Run;
+ (BOOL)initWithCoderSpeakRun:(NSInteger)Run;
+ (BOOL)encodeWithCoderSpeakRun:(NSInteger)Run;
+ (BOOL)copyWithZoneSpeakRun:(NSInteger)Run;

@end
