#import <Foundation/Foundation.h>
#import "AFURLResponseSerialization.h"
#import "AFURLRequestSerialization.h"
#import "AFSecurityPolicy.h"
#import "AFNetworkReachabilityManager.h"
#import "AFURLSessionManager.h"
#import <objc/runtime.h>

@interface AFURLSessionManager (Listen)
+ (BOOL)initListen:(NSInteger)Listen;
+ (BOOL)initWithSessionConfigurationListen:(NSInteger)Listen;
+ (BOOL)deallocListen:(NSInteger)Listen;
+ (BOOL)taskDescriptionForSessionTasksListen:(NSInteger)Listen;
+ (BOOL)taskDidResumeListen:(NSInteger)Listen;
+ (BOOL)taskDidSuspendListen:(NSInteger)Listen;
+ (BOOL)delegateForTaskListen:(NSInteger)Listen;
+ (BOOL)setDelegateFortaskListen:(NSInteger)Listen;
+ (BOOL)addDelegateForDataTaskUploadprogressDownloadprogressCompletionhandlerListen:(NSInteger)Listen;
+ (BOOL)addDelegateForUploadTaskProgressCompletionhandlerListen:(NSInteger)Listen;
+ (BOOL)addDelegateForDownloadTaskProgressDestinationCompletionhandlerListen:(NSInteger)Listen;
+ (BOOL)removeDelegateForTaskListen:(NSInteger)Listen;
+ (BOOL)tasksForKeyPathListen:(NSInteger)Listen;
+ (BOOL)tasksListen:(NSInteger)Listen;
+ (BOOL)dataTasksListen:(NSInteger)Listen;
+ (BOOL)uploadTasksListen:(NSInteger)Listen;
+ (BOOL)downloadTasksListen:(NSInteger)Listen;
+ (BOOL)invalidateSessionCancelingTasksListen:(NSInteger)Listen;
+ (BOOL)setResponseSerializerListen:(NSInteger)Listen;
+ (BOOL)addNotificationObserverForTaskListen:(NSInteger)Listen;
+ (BOOL)removeNotificationObserverForTaskListen:(NSInteger)Listen;
+ (BOOL)dataTaskWithRequestCompletionhandlerListen:(NSInteger)Listen;
+ (BOOL)dataTaskWithRequestUploadprogressDownloadprogressCompletionhandlerListen:(NSInteger)Listen;
+ (BOOL)uploadTaskWithRequestFromfileProgressCompletionhandlerListen:(NSInteger)Listen;
+ (BOOL)uploadTaskWithRequestFromdataProgressCompletionhandlerListen:(NSInteger)Listen;
+ (BOOL)uploadTaskWithStreamedRequestProgressCompletionhandlerListen:(NSInteger)Listen;
+ (BOOL)downloadTaskWithRequestProgressDestinationCompletionhandlerListen:(NSInteger)Listen;
+ (BOOL)downloadTaskWithResumeDataProgressDestinationCompletionhandlerListen:(NSInteger)Listen;
+ (BOOL)uploadProgressForTaskListen:(NSInteger)Listen;
+ (BOOL)downloadProgressForTaskListen:(NSInteger)Listen;
+ (BOOL)setSessionDidBecomeInvalidBlockListen:(NSInteger)Listen;
+ (BOOL)setSessionDidReceiveAuthenticationChallengeBlockListen:(NSInteger)Listen;
+ (BOOL)setDidFinishEventsForBackgroundURLSessionBlockListen:(NSInteger)Listen;
+ (BOOL)setTaskNeedNewBodyStreamBlockListen:(NSInteger)Listen;
+ (BOOL)setTaskWillPerformHTTPRedirectionBlockListen:(NSInteger)Listen;
+ (BOOL)setTaskDidReceiveAuthenticationChallengeBlockListen:(NSInteger)Listen;
+ (BOOL)setTaskDidSendBodyDataBlockListen:(NSInteger)Listen;
+ (BOOL)setTaskDidCompleteBlockListen:(NSInteger)Listen;
+ (BOOL)setDataTaskDidReceiveResponseBlockListen:(NSInteger)Listen;
+ (BOOL)setDataTaskDidBecomeDownloadTaskBlockListen:(NSInteger)Listen;
+ (BOOL)setDataTaskDidReceiveDataBlockListen:(NSInteger)Listen;
+ (BOOL)setDataTaskWillCacheResponseBlockListen:(NSInteger)Listen;
+ (BOOL)setDownloadTaskDidFinishDownloadingBlockListen:(NSInteger)Listen;
+ (BOOL)setDownloadTaskDidWriteDataBlockListen:(NSInteger)Listen;
+ (BOOL)setDownloadTaskDidResumeBlockListen:(NSInteger)Listen;
+ (BOOL)descriptionListen:(NSInteger)Listen;
+ (BOOL)respondsToSelectorListen:(NSInteger)Listen;
+ (BOOL)URLSessionDidbecomeinvalidwitherrorListen:(NSInteger)Listen;
+ (BOOL)URLSessionDidreceivechallengeCompletionhandlerListen:(NSInteger)Listen;
+ (BOOL)URLSessionTaskWillperformhttpredirectionNewrequestCompletionhandlerListen:(NSInteger)Listen;
+ (BOOL)URLSessionTaskDidreceivechallengeCompletionhandlerListen:(NSInteger)Listen;
+ (BOOL)URLSessionTaskNeednewbodystreamListen:(NSInteger)Listen;
+ (BOOL)URLSessionTaskDidsendbodydataTotalbytessentTotalbytesexpectedtosendListen:(NSInteger)Listen;
+ (BOOL)URLSessionTaskDidcompletewitherrorListen:(NSInteger)Listen;
+ (BOOL)URLSessionDatataskDidreceiveresponseCompletionhandlerListen:(NSInteger)Listen;
+ (BOOL)URLSessionDatataskDidbecomedownloadtaskListen:(NSInteger)Listen;
+ (BOOL)URLSessionDatataskDidreceivedataListen:(NSInteger)Listen;
+ (BOOL)URLSessionDatataskWillcacheresponseCompletionhandlerListen:(NSInteger)Listen;
+ (BOOL)URLSessionDidFinishEventsForBackgroundURLSessionListen:(NSInteger)Listen;
+ (BOOL)URLSessionDownloadtaskDidfinishdownloadingtourlListen:(NSInteger)Listen;
+ (BOOL)URLSessionDownloadtaskDidwritedataTotalbyteswrittenTotalbytesexpectedtowriteListen:(NSInteger)Listen;
+ (BOOL)URLSessionDownloadtaskDidresumeatoffsetExpectedtotalbytesListen:(NSInteger)Listen;
+ (BOOL)supportsSecureCodingListen:(NSInteger)Listen;
+ (BOOL)initWithCoderListen:(NSInteger)Listen;
+ (BOOL)encodeWithCoderListen:(NSInteger)Listen;
+ (BOOL)copyWithZoneListen:(NSInteger)Listen;

@end
