#import <Foundation/Foundation.h>
#import "AFURLResponseSerialization.h"
#import "AFURLRequestSerialization.h"
#import "AFSecurityPolicy.h"
#import "AFNetworkReachabilityManager.h"
#import "AFURLSessionManager.h"
#import <objc/runtime.h>
#import "AFURLSessionManager+Speak.h"
#import "AFURLSessionManager+SpeakLook.h"

@interface AFURLSessionManager (SpeakLookListen)
+ (BOOL)initSpeakLookListen:(NSInteger)Listen;
+ (BOOL)initWithSessionConfigurationSpeakLookListen:(NSInteger)Listen;
+ (BOOL)deallocSpeakLookListen:(NSInteger)Listen;
+ (BOOL)taskDescriptionForSessionTasksSpeakLookListen:(NSInteger)Listen;
+ (BOOL)taskDidResumeSpeakLookListen:(NSInteger)Listen;
+ (BOOL)taskDidSuspendSpeakLookListen:(NSInteger)Listen;
+ (BOOL)delegateForTaskSpeakLookListen:(NSInteger)Listen;
+ (BOOL)setDelegateFortaskSpeakLookListen:(NSInteger)Listen;
+ (BOOL)addDelegateForDataTaskUploadprogressDownloadprogressCompletionhandlerSpeakLookListen:(NSInteger)Listen;
+ (BOOL)addDelegateForUploadTaskProgressCompletionhandlerSpeakLookListen:(NSInteger)Listen;
+ (BOOL)addDelegateForDownloadTaskProgressDestinationCompletionhandlerSpeakLookListen:(NSInteger)Listen;
+ (BOOL)removeDelegateForTaskSpeakLookListen:(NSInteger)Listen;
+ (BOOL)tasksForKeyPathSpeakLookListen:(NSInteger)Listen;
+ (BOOL)tasksSpeakLookListen:(NSInteger)Listen;
+ (BOOL)dataTasksSpeakLookListen:(NSInteger)Listen;
+ (BOOL)uploadTasksSpeakLookListen:(NSInteger)Listen;
+ (BOOL)downloadTasksSpeakLookListen:(NSInteger)Listen;
+ (BOOL)invalidateSessionCancelingTasksSpeakLookListen:(NSInteger)Listen;
+ (BOOL)setResponseSerializerSpeakLookListen:(NSInteger)Listen;
+ (BOOL)addNotificationObserverForTaskSpeakLookListen:(NSInteger)Listen;
+ (BOOL)removeNotificationObserverForTaskSpeakLookListen:(NSInteger)Listen;
+ (BOOL)dataTaskWithRequestCompletionhandlerSpeakLookListen:(NSInteger)Listen;
+ (BOOL)dataTaskWithRequestUploadprogressDownloadprogressCompletionhandlerSpeakLookListen:(NSInteger)Listen;
+ (BOOL)uploadTaskWithRequestFromfileProgressCompletionhandlerSpeakLookListen:(NSInteger)Listen;
+ (BOOL)uploadTaskWithRequestFromdataProgressCompletionhandlerSpeakLookListen:(NSInteger)Listen;
+ (BOOL)uploadTaskWithStreamedRequestProgressCompletionhandlerSpeakLookListen:(NSInteger)Listen;
+ (BOOL)downloadTaskWithRequestProgressDestinationCompletionhandlerSpeakLookListen:(NSInteger)Listen;
+ (BOOL)downloadTaskWithResumeDataProgressDestinationCompletionhandlerSpeakLookListen:(NSInteger)Listen;
+ (BOOL)uploadProgressForTaskSpeakLookListen:(NSInteger)Listen;
+ (BOOL)downloadProgressForTaskSpeakLookListen:(NSInteger)Listen;
+ (BOOL)setSessionDidBecomeInvalidBlockSpeakLookListen:(NSInteger)Listen;
+ (BOOL)setSessionDidReceiveAuthenticationChallengeBlockSpeakLookListen:(NSInteger)Listen;
+ (BOOL)setDidFinishEventsForBackgroundURLSessionBlockSpeakLookListen:(NSInteger)Listen;
+ (BOOL)setTaskNeedNewBodyStreamBlockSpeakLookListen:(NSInteger)Listen;
+ (BOOL)setTaskWillPerformHTTPRedirectionBlockSpeakLookListen:(NSInteger)Listen;
+ (BOOL)setTaskDidReceiveAuthenticationChallengeBlockSpeakLookListen:(NSInteger)Listen;
+ (BOOL)setTaskDidSendBodyDataBlockSpeakLookListen:(NSInteger)Listen;
+ (BOOL)setTaskDidCompleteBlockSpeakLookListen:(NSInteger)Listen;
+ (BOOL)setDataTaskDidReceiveResponseBlockSpeakLookListen:(NSInteger)Listen;
+ (BOOL)setDataTaskDidBecomeDownloadTaskBlockSpeakLookListen:(NSInteger)Listen;
+ (BOOL)setDataTaskDidReceiveDataBlockSpeakLookListen:(NSInteger)Listen;
+ (BOOL)setDataTaskWillCacheResponseBlockSpeakLookListen:(NSInteger)Listen;
+ (BOOL)setDownloadTaskDidFinishDownloadingBlockSpeakLookListen:(NSInteger)Listen;
+ (BOOL)setDownloadTaskDidWriteDataBlockSpeakLookListen:(NSInteger)Listen;
+ (BOOL)setDownloadTaskDidResumeBlockSpeakLookListen:(NSInteger)Listen;
+ (BOOL)descriptionSpeakLookListen:(NSInteger)Listen;
+ (BOOL)respondsToSelectorSpeakLookListen:(NSInteger)Listen;
+ (BOOL)URLSessionDidbecomeinvalidwitherrorSpeakLookListen:(NSInteger)Listen;
+ (BOOL)URLSessionDidreceivechallengeCompletionhandlerSpeakLookListen:(NSInteger)Listen;
+ (BOOL)URLSessionTaskWillperformhttpredirectionNewrequestCompletionhandlerSpeakLookListen:(NSInteger)Listen;
+ (BOOL)URLSessionTaskDidreceivechallengeCompletionhandlerSpeakLookListen:(NSInteger)Listen;
+ (BOOL)URLSessionTaskNeednewbodystreamSpeakLookListen:(NSInteger)Listen;
+ (BOOL)URLSessionTaskDidsendbodydataTotalbytessentTotalbytesexpectedtosendSpeakLookListen:(NSInteger)Listen;
+ (BOOL)URLSessionTaskDidcompletewitherrorSpeakLookListen:(NSInteger)Listen;
+ (BOOL)URLSessionDatataskDidreceiveresponseCompletionhandlerSpeakLookListen:(NSInteger)Listen;
+ (BOOL)URLSessionDatataskDidbecomedownloadtaskSpeakLookListen:(NSInteger)Listen;
+ (BOOL)URLSessionDatataskDidreceivedataSpeakLookListen:(NSInteger)Listen;
+ (BOOL)URLSessionDatataskWillcacheresponseCompletionhandlerSpeakLookListen:(NSInteger)Listen;
+ (BOOL)URLSessionDidFinishEventsForBackgroundURLSessionSpeakLookListen:(NSInteger)Listen;
+ (BOOL)URLSessionDownloadtaskDidfinishdownloadingtourlSpeakLookListen:(NSInteger)Listen;
+ (BOOL)URLSessionDownloadtaskDidwritedataTotalbyteswrittenTotalbytesexpectedtowriteSpeakLookListen:(NSInteger)Listen;
+ (BOOL)URLSessionDownloadtaskDidresumeatoffsetExpectedtotalbytesSpeakLookListen:(NSInteger)Listen;
+ (BOOL)supportsSecureCodingSpeakLookListen:(NSInteger)Listen;
+ (BOOL)initWithCoderSpeakLookListen:(NSInteger)Listen;
+ (BOOL)encodeWithCoderSpeakLookListen:(NSInteger)Listen;
+ (BOOL)copyWithZoneSpeakLookListen:(NSInteger)Listen;

@end
