#import <Foundation/Foundation.h>
#import "EatMASConstraintc.h"

@interface EatMASConstraintc (Dance)
+ (BOOL)GInitsingDance:(NSInteger)Dance;
+ (BOOL)iEqualtosingDance:(NSInteger)Dance;
+ (BOOL)DMas_EqualtosingDance:(NSInteger)Dance;
+ (BOOL)VGreaterthanorequaltosingDance:(NSInteger)Dance;
+ (BOOL)zMas_GreaterthanorequaltosingDance:(NSInteger)Dance;
+ (BOOL)nLessthanorequaltosingDance:(NSInteger)Dance;
+ (BOOL)SMas_LessthanorequaltosingDance:(NSInteger)Dance;
+ (BOOL)MPrioritylowsingDance:(NSInteger)Dance;
+ (BOOL)wPrioritymediumsingDance:(NSInteger)Dance;
+ (BOOL)IPriorityhighsingDance:(NSInteger)Dance;
+ (BOOL)lInsetssingDance:(NSInteger)Dance;
+ (BOOL)ZInsetsingDance:(NSInteger)Dance;
+ (BOOL)KSizeoffsetsingDance:(NSInteger)Dance;
+ (BOOL)pCenteroffsetsingDance:(NSInteger)Dance;
+ (BOOL)wOffsetsingDance:(NSInteger)Dance;
+ (BOOL)WValueoffsetsingDance:(NSInteger)Dance;
+ (BOOL)QMas_OffsetsingDance:(NSInteger)Dance;
+ (BOOL)QSetlayoutconstantwithvaluesingDance:(NSInteger)Dance;
+ (BOOL)wWithsingDance:(NSInteger)Dance;
+ (BOOL)uAndsingDance:(NSInteger)Dance;
+ (BOOL)SAddconstraintwithlayoutattributesingDance:(NSInteger)Dance;
+ (BOOL)lLeftsingDance:(NSInteger)Dance;
+ (BOOL)ATopsingDance:(NSInteger)Dance;
+ (BOOL)ZRightsingDance:(NSInteger)Dance;
+ (BOOL)EBottomsingDance:(NSInteger)Dance;
+ (BOOL)tLeadingsingDance:(NSInteger)Dance;
+ (BOOL)fTrailingsingDance:(NSInteger)Dance;
+ (BOOL)zWidthsingDance:(NSInteger)Dance;
+ (BOOL)dHeightsingDance:(NSInteger)Dance;
+ (BOOL)TCenterxsingDance:(NSInteger)Dance;
+ (BOOL)vCenterysingDance:(NSInteger)Dance;
+ (BOOL)xBaselinesingDance:(NSInteger)Dance;
+ (BOOL)dFirstbaselinesingDance:(NSInteger)Dance;
+ (BOOL)kLastbaselinesingDance:(NSInteger)Dance;
+ (BOOL)iLeftmarginsingDance:(NSInteger)Dance;
+ (BOOL)BRightmarginsingDance:(NSInteger)Dance;
+ (BOOL)ETopmarginsingDance:(NSInteger)Dance;
+ (BOOL)dBottommarginsingDance:(NSInteger)Dance;
+ (BOOL)aLeadingmarginsingDance:(NSInteger)Dance;
+ (BOOL)lTrailingmarginsingDance:(NSInteger)Dance;
+ (BOOL)dCenterxwithinmarginssingDance:(NSInteger)Dance;
+ (BOOL)bCenterywithinmarginssingDance:(NSInteger)Dance;
+ (BOOL)LMultipliedbysingDance:(NSInteger)Dance;
+ (BOOL)xDividedbysingDance:(NSInteger)Dance;
+ (BOOL)QPrioritysingDance:(NSInteger)Dance;
+ (BOOL)JEqualtowithrelationsingDance:(NSInteger)Dance;
+ (BOOL)LKeysingDance:(NSInteger)Dance;
+ (BOOL)fSetinsetssingDance:(NSInteger)Dance;
+ (BOOL)jSetinsetsingDance:(NSInteger)Dance;
+ (BOOL)xSetsizeoffsetsingDance:(NSInteger)Dance;
+ (BOOL)ISetcenteroffsetsingDance:(NSInteger)Dance;
+ (BOOL)ISetoffsetsingDance:(NSInteger)Dance;
+ (BOOL)xAnimatorsingDance:(NSInteger)Dance;
+ (BOOL)cActivatesingDance:(NSInteger)Dance;
+ (BOOL)FDeactivatesingDance:(NSInteger)Dance;
+ (BOOL)sInstallsingDance:(NSInteger)Dance;
+ (BOOL)eUninstallsingDance:(NSInteger)Dance;

@end
