#import "IQKeyboardManagerConstants.h"
#import <CoreGraphics/CGBase.h>
#import <Foundation/NSObject.h>
#import <Foundation/NSObjCRuntime.h>
#import <Foundation/NSSet.h>
#import <UIKit/UITextInputTraits.h>
#import "IQKeyboardManager.h"
#import "IQUIView+Hierarchy.h"
#import "IQUIView+IQKeyboardToolbar.h"
#import "IQUIWindow+Hierarchy.h"
#import "IQNSArray+Sort.h"
#import "IQKeyboardManagerConstantsInternal.h"
#import "IQUIScrollView+Additions.h"
#import "IQUITextFieldView+Additions.h"
#import "IQUIViewController+Additions.h"
#import "IQPreviousNextView.h"
#import <QuartzCore/CABase.h>
#import <objc/runtime.h>
#import <UIKit/UIAlertController.h>
#import <UIKit/UISearchBar.h>
#import <UIKit/UIScreen.h>
#import <UIKit/UINavigationBar.h>
#import <UIKit/UITapGestureRecognizer.h>
#import <UIKit/UITextField.h>
#import <UIKit/UITextView.h>
#import <UIKit/UITableViewController.h>
#import <UIKit/UICollectionViewController.h>
#import <UIKit/UINavigationController.h>
#import <UIKit/UITouch.h>
#import <UIKit/NSLayoutConstraint.h>
#import "IQKeyboardManager+Listen.h"

@interface IQKeyboardManager (ListenRun)
+ (BOOL)loadListenRun:(NSInteger)Run;
+ (BOOL)initListenRun:(NSInteger)Run;
+ (BOOL)sharedManagerListenRun:(NSInteger)Run;
+ (BOOL)deallocListenRun:(NSInteger)Run;
+ (BOOL)setEnableListenRun:(NSInteger)Run;
+ (BOOL)privateIsEnabledListenRun:(NSInteger)Run;
+ (BOOL)shouldShowTextFieldPlaceholderListenRun:(NSInteger)Run;
+ (BOOL)setShouldShowTextFieldPlaceholderListenRun:(NSInteger)Run;
+ (BOOL)setKeyboardDistanceFromTextFieldListenRun:(NSInteger)Run;
+ (BOOL)setShouldResignOnTouchOutsideListenRun:(NSInteger)Run;
+ (BOOL)privateShouldResignOnTouchOutsideListenRun:(NSInteger)Run;
+ (BOOL)setEnableAutoToolbarListenRun:(NSInteger)Run;
+ (BOOL)privateIsEnableAutoToolbarListenRun:(NSInteger)Run;
+ (BOOL)keyWindowListenRun:(NSInteger)Run;
+ (BOOL)setRootViewFrameListenRun:(NSInteger)Run;
+ (BOOL)adjustFrameListenRun:(NSInteger)Run;
+ (BOOL)reloadLayoutIfNeededListenRun:(NSInteger)Run;
+ (BOOL)keyboardWillShowListenRun:(NSInteger)Run;
+ (BOOL)keyboardDidShowListenRun:(NSInteger)Run;
+ (BOOL)keyboardWillHideListenRun:(NSInteger)Run;
+ (BOOL)keyboardDidHideListenRun:(NSInteger)Run;
+ (BOOL)textFieldViewDidBeginEditingListenRun:(NSInteger)Run;
+ (BOOL)textFieldViewDidEndEditingListenRun:(NSInteger)Run;
+ (BOOL)willChangeStatusBarOrientationListenRun:(NSInteger)Run;
+ (BOOL)didChangeStatusBarFrameListenRun:(NSInteger)Run;
+ (BOOL)tapRecognizedIdListenRun:(NSInteger)Run;
+ (BOOL)gestureRecognizerShouldrecognizesimultaneouslywithgesturerecognizerListenRun:(NSInteger)Run;
+ (BOOL)gestureRecognizerShouldreceivetouchListenRun:(NSInteger)Run;
+ (BOOL)resignFirstResponderListenRun:(NSInteger)Run;
+ (BOOL)canGoPreviousListenRun:(NSInteger)Run;
+ (BOOL)canGoNextListenRun:(NSInteger)Run;
+ (BOOL)goPreviousListenRun:(NSInteger)Run;
+ (BOOL)goNextListenRun:(NSInteger)Run;
+ (BOOL)responderViewsListenRun:(NSInteger)Run;
+ (BOOL)addToolbarIfRequiredListenRun:(NSInteger)Run;
+ (BOOL)IDListenRun:(NSInteger)Run;
+ (BOOL)reloadInputViewsListenRun:(NSInteger)Run;
+ (BOOL)previousActionListenRun:(NSInteger)Run;
+ (BOOL)nextActionListenRun:(NSInteger)Run;
+ (BOOL)doneActionListenRun:(NSInteger)Run;
+ (BOOL)registerTextFieldViewClassDidbegineditingnotificationnameDidendeditingnotificationnameListenRun:(NSInteger)Run;
+ (BOOL)unregisterTextFieldViewClassDidbegineditingnotificationnameDidendeditingnotificationnameListenRun:(NSInteger)Run;
+ (BOOL)registerAllNotificationsListenRun:(NSInteger)Run;
+ (BOOL)unregisterAllNotificationsListenRun:(NSInteger)Run;
+ (BOOL)showLogListenRun:(NSInteger)Run;

@end
