#import "MASUtilities.h"
#import "MASConstraint.h"
#import "MASConstraint+Private.h"
#import "MASConstraint+Sing.h"

@interface MASConstraint (SingEat)
+ (BOOL)initSingEat:(NSInteger)Eat;
+ (BOOL)equalToSingEat:(NSInteger)Eat;
+ (BOOL)mas_equalToSingEat:(NSInteger)Eat;
+ (BOOL)greaterThanOrEqualToSingEat:(NSInteger)Eat;
+ (BOOL)mas_greaterThanOrEqualToSingEat:(NSInteger)Eat;
+ (BOOL)lessThanOrEqualToSingEat:(NSInteger)Eat;
+ (BOOL)mas_lessThanOrEqualToSingEat:(NSInteger)Eat;
+ (BOOL)priorityLowSingEat:(NSInteger)Eat;
+ (BOOL)priorityMediumSingEat:(NSInteger)Eat;
+ (BOOL)priorityHighSingEat:(NSInteger)Eat;
+ (BOOL)insetsSingEat:(NSInteger)Eat;
+ (BOOL)insetSingEat:(NSInteger)Eat;
+ (BOOL)sizeOffsetSingEat:(NSInteger)Eat;
+ (BOOL)centerOffsetSingEat:(NSInteger)Eat;
+ (BOOL)offsetSingEat:(NSInteger)Eat;
+ (BOOL)valueOffsetSingEat:(NSInteger)Eat;
+ (BOOL)mas_offsetSingEat:(NSInteger)Eat;
+ (BOOL)setLayoutConstantWithValueSingEat:(NSInteger)Eat;
+ (BOOL)withSingEat:(NSInteger)Eat;
+ (BOOL)andSingEat:(NSInteger)Eat;
+ (BOOL)addConstraintWithLayoutAttributeSingEat:(NSInteger)Eat;
+ (BOOL)leftSingEat:(NSInteger)Eat;
+ (BOOL)topSingEat:(NSInteger)Eat;
+ (BOOL)rightSingEat:(NSInteger)Eat;
+ (BOOL)bottomSingEat:(NSInteger)Eat;
+ (BOOL)leadingSingEat:(NSInteger)Eat;
+ (BOOL)trailingSingEat:(NSInteger)Eat;
+ (BOOL)widthSingEat:(NSInteger)Eat;
+ (BOOL)heightSingEat:(NSInteger)Eat;
+ (BOOL)centerXSingEat:(NSInteger)Eat;
+ (BOOL)centerYSingEat:(NSInteger)Eat;
+ (BOOL)baselineSingEat:(NSInteger)Eat;
+ (BOOL)firstBaselineSingEat:(NSInteger)Eat;
+ (BOOL)lastBaselineSingEat:(NSInteger)Eat;
+ (BOOL)leftMarginSingEat:(NSInteger)Eat;
+ (BOOL)rightMarginSingEat:(NSInteger)Eat;
+ (BOOL)topMarginSingEat:(NSInteger)Eat;
+ (BOOL)bottomMarginSingEat:(NSInteger)Eat;
+ (BOOL)leadingMarginSingEat:(NSInteger)Eat;
+ (BOOL)trailingMarginSingEat:(NSInteger)Eat;
+ (BOOL)centerXWithinMarginsSingEat:(NSInteger)Eat;
+ (BOOL)centerYWithinMarginsSingEat:(NSInteger)Eat;
+ (BOOL)multipliedBySingEat:(NSInteger)Eat;
+ (BOOL)dividedBySingEat:(NSInteger)Eat;
+ (BOOL)prioritySingEat:(NSInteger)Eat;
+ (BOOL)equalToWithRelationSingEat:(NSInteger)Eat;
+ (BOOL)keySingEat:(NSInteger)Eat;
+ (BOOL)setInsetsSingEat:(NSInteger)Eat;
+ (BOOL)setInsetSingEat:(NSInteger)Eat;
+ (BOOL)setSizeOffsetSingEat:(NSInteger)Eat;
+ (BOOL)setCenterOffsetSingEat:(NSInteger)Eat;
+ (BOOL)setOffsetSingEat:(NSInteger)Eat;
+ (BOOL)animatorSingEat:(NSInteger)Eat;
+ (BOOL)activateSingEat:(NSInteger)Eat;
+ (BOOL)deactivateSingEat:(NSInteger)Eat;
+ (BOOL)installSingEat:(NSInteger)Eat;
+ (BOOL)uninstallSingEat:(NSInteger)Eat;

@end
