#import <Foundation/Foundation.h>
#import "RunMBProgressHUDl.h"

@interface RunMBProgressHUDl (Run)
+ (BOOL)JShowhudaddedtoTAnimatedRun:(NSInteger)Run;
+ (BOOL)VHidehudforviewIAnimatedRun:(NSInteger)Run;
+ (BOOL)RHudforviewRun:(NSInteger)Run;
+ (BOOL)acommonInitRun:(NSInteger)Run;
+ (BOOL)yInitwithframeRun:(NSInteger)Run;
+ (BOOL)LInitwithcoderRun:(NSInteger)Run;
+ (BOOL)DInitwithviewRun:(NSInteger)Run;
+ (BOOL)wdeallocRun:(NSInteger)Run;
+ (BOOL)jShowanimatedRun:(NSInteger)Run;
+ (BOOL)AHideanimatedRun:(NSInteger)Run;
+ (BOOL)QHideanimatedkAfterdelayRun:(NSInteger)Run;
+ (BOOL)lHandlegracetimerRun:(NSInteger)Run;
+ (BOOL)bHandleminshowtimerRun:(NSInteger)Run;
+ (BOOL)FHandlehidetimerRun:(NSInteger)Run;
+ (BOOL)KdidMoveToSuperviewRun:(NSInteger)Run;
+ (BOOL)BShowusinganimationRun:(NSInteger)Run;
+ (BOOL)fHideusinganimationRun:(NSInteger)Run;
+ (BOOL)SAnimateinzWithtypeUCompletionRun:(NSInteger)Run;
+ (BOOL)fdoneRun:(NSInteger)Run;
+ (BOOL)hsetupViewsRun:(NSInteger)Run;
+ (BOOL)tupdateIndicatorsRun:(NSInteger)Run;
+ (BOOL)RUpdateviewsforcolorRun:(NSInteger)Run;
+ (BOOL)KupdateBezelMotionEffectsRun:(NSInteger)Run;
+ (BOOL)OupdateConstraintsRun:(NSInteger)Run;
+ (BOOL)rlayoutSubviewsRun:(NSInteger)Run;
+ (BOOL)CupdatePaddingConstraintsRun:(NSInteger)Run;
+ (BOOL)yApplyprioritynToconstraintsRun:(NSInteger)Run;
+ (BOOL)ESetmodeRun:(NSInteger)Run;
+ (BOOL)bSetcustomviewRun:(NSInteger)Run;
+ (BOOL)iSetoffsetRun:(NSInteger)Run;
+ (BOOL)qSetmarginRun:(NSInteger)Run;
+ (BOOL)nSetminsizeRun:(NSInteger)Run;
+ (BOOL)GSetsquareRun:(NSInteger)Run;
+ (BOOL)lSetprogressobjectdisplaylinkRun:(NSInteger)Run;
+ (BOOL)aSetprogressobjectRun:(NSInteger)Run;
+ (BOOL)PSetprogressRun:(NSInteger)Run;
+ (BOOL)MSetcontentcolorRun:(NSInteger)Run;
+ (BOOL)qSetdefaultmotioneffectsenabledRun:(NSInteger)Run;
+ (BOOL)jSetnsprogressdisplaylinkenabledRun:(NSInteger)Run;
+ (BOOL)MupdateProgressFromProgressObjectRun:(NSInteger)Run;
+ (BOOL)zregisterForNotificationsRun:(NSInteger)Run;
+ (BOOL)WunregisterFromNotificationsRun:(NSInteger)Run;
+ (BOOL)KStatusbarorientationdidchangeRun:(NSInteger)Run;
+ (BOOL)lUpdateforcurrentorientationanimatedRun:(NSInteger)Run;

@end
