#import <Foundation/Foundation.h>
#import "SingMASConstraintY.h"

@interface SingMASConstraintY (Look)
+ (BOOL)hinitLook:(NSInteger)Look;
+ (BOOL)equalToLook:(NSInteger)Look;
+ (BOOL)mas_equalToLook:(NSInteger)Look;
+ (BOOL)greaterThanOrEqualToLook:(NSInteger)Look;
+ (BOOL)mas_greaterThanOrEqualToLook:(NSInteger)Look;
+ (BOOL)lessThanOrEqualToLook:(NSInteger)Look;
+ (BOOL)mas_lessThanOrEqualToLook:(NSInteger)Look;
+ (BOOL)priorityLowLook:(NSInteger)Look;
+ (BOOL)priorityMediumLook:(NSInteger)Look;
+ (BOOL)priorityHighLook:(NSInteger)Look;
+ (BOOL)insetsLook:(NSInteger)Look;
+ (BOOL)insetLook:(NSInteger)Look;
+ (BOOL)sizeOffsetLook:(NSInteger)Look;
+ (BOOL)centerOffsetLook:(NSInteger)Look;
+ (BOOL)offsetLook:(NSInteger)Look;
+ (BOOL)valueOffsetLook:(NSInteger)Look;
+ (BOOL)mas_offsetLook:(NSInteger)Look;
+ (BOOL)jSetlayoutconstantwithvalueLook:(NSInteger)Look;
+ (BOOL)PwithLook:(NSInteger)Look;
+ (BOOL)SandLook:(NSInteger)Look;
+ (BOOL)cAddconstraintwithlayoutattributeLook:(NSInteger)Look;
+ (BOOL)eleftLook:(NSInteger)Look;
+ (BOOL)etopLook:(NSInteger)Look;
+ (BOOL)VrightLook:(NSInteger)Look;
+ (BOOL)ebottomLook:(NSInteger)Look;
+ (BOOL)XleadingLook:(NSInteger)Look;
+ (BOOL)utrailingLook:(NSInteger)Look;
+ (BOOL)cwidthLook:(NSInteger)Look;
+ (BOOL)dheightLook:(NSInteger)Look;
+ (BOOL)ZcenterXLook:(NSInteger)Look;
+ (BOOL)FcenterYLook:(NSInteger)Look;
+ (BOOL)nbaselineLook:(NSInteger)Look;
+ (BOOL)kfirstBaselineLook:(NSInteger)Look;
+ (BOOL)HlastBaselineLook:(NSInteger)Look;
+ (BOOL)OleftMarginLook:(NSInteger)Look;
+ (BOOL)UrightMarginLook:(NSInteger)Look;
+ (BOOL)stopMarginLook:(NSInteger)Look;
+ (BOOL)rbottomMarginLook:(NSInteger)Look;
+ (BOOL)rleadingMarginLook:(NSInteger)Look;
+ (BOOL)TtrailingMarginLook:(NSInteger)Look;
+ (BOOL)lcenterXWithinMarginsLook:(NSInteger)Look;
+ (BOOL)hcenterYWithinMarginsLook:(NSInteger)Look;
+ (BOOL)multipliedByLook:(NSInteger)Look;
+ (BOOL)dividedByLook:(NSInteger)Look;
+ (BOOL)priorityLook:(NSInteger)Look;
+ (BOOL)equalToWithRelationLook:(NSInteger)Look;
+ (BOOL)keyLook:(NSInteger)Look;
+ (BOOL)fSetinsetsLook:(NSInteger)Look;
+ (BOOL)SSetinsetLook:(NSInteger)Look;
+ (BOOL)QSetsizeoffsetLook:(NSInteger)Look;
+ (BOOL)FSetcenteroffsetLook:(NSInteger)Look;
+ (BOOL)HSetoffsetLook:(NSInteger)Look;
+ (BOOL)GanimatorLook:(NSInteger)Look;
+ (BOOL)MactivateLook:(NSInteger)Look;
+ (BOOL)kdeactivateLook:(NSInteger)Look;
+ (BOOL)KinstallLook:(NSInteger)Look;
+ (BOOL)TuninstallLook:(NSInteger)Look;

@end
